---
title: "1_load_merge_clean"
author: "ASM"
date: "19/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(lubridate)
library(broom)
library(janitor)
library(knitr)
library(patchwork)
```




```{r load anonymized data sets}

load(here("anonymized_data/LEQ_data.Rda"))

 load(here("anonymized_data/demographic_data.Rda"))
 
#rename
 LEQ_data <- final_fam_str
 demographic_data <- demog_anonym
```


```{r clean datasets to allow merging}
#gets gender under a unified scale, as it had different scales for different studies
demographic_data <- demographic_data %>%
  mutate(gender=case_when(
    gender %in% c("male", "M") ~ "male",
    gender %in% c("female", "F") ~ "female",
    gender == 1 ~ "male",
    gender == 0 ~ "female")) 

#renames studies to make paralell to the way they are named in the LEQ data.
demographic_data <- demographic_data %>%
  mutate(study = tolower(study)) %>%
  mutate(study = case_when(study =="cogmisp" ~ "cogmisp24",
                           study=="faceprince-12"~"faceprince12",
                           study=="faceprince-18"~"faceprince18",
                           study=="littlemix-8"~"littlemix8",
                           study=="many_babies_12"~"manybabies12",
                           study=="many_babies_6"~"manybabies6",
                           study=="segment_8"~"segment8",
                   TRUE ~ study)) %>% 
  mutate(unique_id = paste(anon_baby_id, study, sep="_")) #creates a unique identifier per each baby per each study

#gets rid of duplicated demographic data 
demographic_data <- demographic_data %>%
  add_count(unique_id) %>%
  filter(n==1)

#adding unique identifier to LEQ data
LEQ_data <-
  LEQ_data %>%
  mutate(study = tolower(study)) %>% 
  mutate(unique_id = paste(anon_baby_id, study, sep="_"))
```


```{r merge demographics and LEQ data}
final_data <-
  right_join(demographic_data, LEQ_data ,  by= c("unique_id", "study", "anon_baby_id"))


#clean date of birth error in one participant
final_data <- final_data %>%
  mutate(leq_date = as.character(leq_date))

final_data$leq_date[final_data$leq_date== "2016-08-07"] <- "2017-03-28"
```


```{r create an age column and save before exclusions}

final_data$do_birth<-as.Date(as.character(final_data$do_birth))
final_data$leq_date<-as.Date(as.character(final_data$leq_date))
final_data <- final_data %>%
  mutate(age= interval(start= do_birth, end=leq_date)/                      
           duration(n=1, unit="months"))

#Create a type of family column. NOTE this column was created after thoroughly reviewing parents' answers and it reflects the places where it was explicitly noted that a child had two same-gender caregivers, or where it is obvious by the parents answers that the child has a single caregiver. Otherwise it was assumed that the child had a mother and a father, and that mothers' answers were entered in the caregiver 1 slot, as it is explicitly instructed in the questionnaire.

final_data <- final_data %>%
  mutate (type_of_family= case_when(anon_baby_id == 5815080 ~ "same_sex_parents",
                                    anon_baby_id == 5373360 ~ "same_sex_parents",
                                    care1_l1 %in% c("never", "NA") & care1_l2 %in% c("never", "NA") & care1_l3 %in% c("never", "NA") & care1_l4 %in% c("never", "NA") ~ "single-parent",
                                    care2_l1 %in% c("never", "NA") & care2_l2 %in% c("never", "NA") & care2_l3 %in% c("never", "NA") & care2_l4 %in% c("never", "NA") ~ "single-parent",
                                    TRUE ~ "mother-father family"))

#save data before exclusions

final_data_no_exc<- final_data

save(final_data_no_exc, file=here("anonymized_data/final_data_no_exc.Rda"))
```


```{r trilingual exclusions and save after exclusions}



final_data <- final_data %>%
  group_by(unique_id, exp_l1, exp_l2)%>%
   mutate(total_l1_l2_exp=(sum(exp_l1,exp_l2,na.rm = T))) %>%
  ungroup() %>%
  filter(total_l1_l2_exp>=90) #59 exclusions for more than 10% exposure to a third language

save(final_data, file=here("anonymized_data/final_merged_data.Rda"))
```

```{r creating the french, english, and heritage exposure variables}
##NOTE: Originally I had also added exposure on language 3 and 4. Language 3 and 4 always amount to less than 10% because we excluded trilinguals. However, 
#in parental interviews caregivers frequently give a third language and the final calculation is so low it amounts to 0 
#this was 0 inflating our english and french exposures, and because we are interested in how bilingual strategies relate to bilingual exposure, I decided to get rid of l3 and 4 exposure when making the french, english, and heritage language exposure variables.
            
  

vars<-c("exp_l3", "exp_l4")

final_data <-
  final_data %>%
 mutate_at(vars, as.numeric) %>%
  mutate(l3 = replace(l3, l3=="NA", "no lang")) %>%
  mutate(l4 = replace(l4, l4=="NA", "no lang")) %>%
  mutate(fre_exp = case_when(l1=="French"~ exp_l1,
                                l2=="French"~ exp_l2,
                                
                             #l3=="French" & exp_l3 >=1 ~ exp_l3, 
                             #l4=="French"  & exp_l4 >=1 ~ exp_l4
                             ))%>%
    mutate(eng_exp = case_when(l1=="English"~ exp_l1,
                                l2=="English"~ exp_l2,
                                #l3=="English"~ exp_l3,
                                #l4=="English"~ exp_l4
                               )) %>%
  mutate(min_exp = case_when (!(l1 %in% c("French", "English"))& l2 %in% c("French", "English") ~ exp_l1,
                              !(l2 %in% c("French", "English")) & l1 %in% c("French", "English") ~ exp_l2
                              ))

```


```{r categorizing family language strategies }

final_data_strat <- final_data %>%
  mutate(strategy=case_when(
    
  #one-parent-one-lang-strict: Each parent speaks only one language and both parents don't speak the same language
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1 %in% c("never", "NA") & care2_l2=="regularly"~ "one-parent-one-lang",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "one-parent-one-lang",
    
  #one-parent-one-lang-flex: Each parent speaks mainly one language, and one of them sometimes speaks another language
  #(The same language cannot be spoken regularly by both parents or that would be considered a one-parent-bilingual strategy)
    #**NOTE: we ended up having a single category for OPOL instead of divinding it into strict and flex.
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="sometimes" &care2_l2=="regularly"~ "one-parent-one-lang",
    care1_l1=="regularly" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") &care2_l2=="regularly"~ "one-parent-one-lang",
    care1_l1=="sometimes" & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "one-parent-one-lang",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2=="sometimes"~ "one-parent-one-lang",
    
    
  #one-parent-bilingual: One parent speaks 2 languages, the other parent only speaks one language
    
    #Starting point
    care1_l1== "regularly" & care1_l2=="regularly" & care2_l1 == "regularly" & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1== "regularly" & care1_l2=="regularly" & care2_l1 %in% c("never", "NA") & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1== "regularly" & care1_l2 %in% c("never", "NA") & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",

    #Some bilingual parents put both of their languages as sometimes rather than both as regularly
    care1_l1== "sometimes" & care1_l2=="sometimes" & care2_l1 == "regularly" & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1== "sometimes" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1== "regularly" & care1_l2 %in% c("never", "NA") & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",

    #One parent bilingual (R&R or S&S) and another parent that speaks one of the language but not the other (R|S & N|NA)
    care1_l1 == "regularly" & care1_l2=="regularly" & care2_l1 %in% c("regularly", "sometimes") & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1 == "regularly" & care1_l2=="regularly" & care2_l1 %in% c("never", "NA") & care2_l2 %in% c("regularly", "sometimes") ~ "one-parent-bilingual",
    care1_l1 %in% c("regularly", "sometimes") & care1_l2 %in% c("never", "NA") & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2 %in% c("regularly", "sometimes") & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",

    care1_l1 == "sometimes" & care1_l2=="sometimes" & care2_l1 %in% c("regularly", "sometimes") & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1 == "sometimes" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") & care2_l2 %in% c("regularly", "sometimes") ~ "one-parent-bilingual",
    care1_l1 %in% c("regularly", "sometimes") & care1_l2 %in% c("never", "NA") & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2 %in% c("regularly", "sometimes") & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    
    #Both parents speak the same language regularly, and one of them speak another language sometimes 
    #(not one-parent-one-lang-flex because both parents use the same language regularly in opposition to each parent having a different language that they use regularly)
    care1_l1=="regularly" & care1_l2=="sometimes" & care2_l1=="regularly" & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="regularly" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    care1_l1=="sometimes" & care1_l2=="regularly" & care2_l1 %in% c("never", "NA")& care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="sometimes" & care2_l2=="regularly" ~ "one-parent-bilingual",
    
    
  #both-parents-bilingual: Both parents speak both languages either regularly or sometimes
    care1_l1%in% c("regularly", "sometimes") & care1_l2%in% c("regularly", "sometimes") & care2_l1%in% c("regularly", "sometimes") &care2_l2%in% c("regularly", "sometimes") ~ "both-parents-bilingual",

  #one-parent-one-lang-flex: Each parent speaks mainly one language, and one of them sometimes speaks another language
  #The same language cannot be spoken regularly by both parents or it comes to be filled under the one-parent-bilingual strategy.
  #**NOTE: we ended up having a single category for OPOL instead of divinding it into strict and flex.
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="sometimes" &care2_l2=="regularly"~ "one-parent-one-lang",
    care1_l1=="regularly" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") &care2_l2=="regularly"~ "one-parent-one-lang",
    care1_l1=="sometimes" & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "one-parent-one-lang",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2=="sometimes"~ "one-parent-one-lang",
    
  #one-language-at-home: There is only one language spoken in the home by both parents
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "one-language-at-home",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1 %in% c("never", "NA") & care2_l2=="regularly"~ "one-language-at-home",
    
    care1_l1=="sometimes" & care1_l2 %in% c("never", "NA") & care2_l1=="sometimes" &care2_l2 %in% c("never", "NA")~ "one-language-at-home",
    care1_l1 %in% c("never", "NA") & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") & care2_l2=="sometimes"~ "one-language-at-home",
    
  #single-parent: Family in which there is only one caregiver
    care1_l1 %in% c("never", "NA") & care1_l2 %in% c("never", "NA") & care1_l3 %in% c("never", "NA") & care1_l4 %in% c("never", "NA") ~ "single-parent",
    care2_l1 %in% c("never", "NA") & care2_l2 %in% c("never", "NA") & care2_l3 %in% c("never", "NA") & care2_l4 %in% c("never", "NA") ~ "single-parent"
  
    ))

```

```{r monolingual exclusions and save dataset with categorized strategies}

# I decided to exclude "true" monolinguals characterized here to the best of our abilities as children whose families use one language at home strategy, and the childcare language is the same as the one language at home strategy = they are being exposed to a single language = most likely not a bilingual strategy.

final_data_strat <-
  final_data_strat %>%
  mutate(bilinugal_strategy= case_when(strategy=="one-language-at-home" & childcare_l1 == l1 & childcare_l2 %in% c(NA, "NA")  ~ "no",
                                       strategy=="one-language-at-home" & childcare_l2 == l1 & childcare_l1 %in% c(NA, "NA") ~"no",
                                       strategy=="one-language-at-home" & childcare_l1 %in% c(NA, "NA") & childcare_l2 %in% c(NA, "NA") ~"no",
                                       TRUE~"yes")) %>%
  filter(bilinugal_strategy=="yes")

#In the end, after discussion we decided to filter all the strictly monolinguals because we are truly interested in bilinguals mainly.

final_data_strat <- 
  final_data_strat %>%
  filter(exp_l1 <95) %>%
  filter(exp_l2 >5)

#save(final_data_strat, file=here("anonymized_data/final_data_strat.Rda"))

```

```{r make and save longitudinal dataset}
#keeps only data where the baby participated more than once
longitudinal_data<- final_data_strat %>%
  add_count(anon_baby_id) %>%
  filter(nn>1)

#save(longitudinal_data, file=here("anonymized_data/longitudinal_data.Rda"))


```

#### Extra

```{r EXPLORATORY datsa set with OPOL strategy divided between strict and flexible}

final_data_strat_2opol <- final_data_language_coded%>%
  mutate(strategy=case_when(
    
  #one-parent-one-lang-strict: Each parent speaks only one language and both parents don't speak the same language
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1 %in% c("never", "NA") & care2_l2=="regularly"~ "OPOL_S",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "OPOL_S",
    
  #one-parent-one-lang-flex: Each parent speaks mainly one language, and one of them sometimes speaks another language
  #(The same language cannot be spoken regularly by both parents or that would be considered a one-parent-bilingual strategy)
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="sometimes" &care2_l2=="regularly"~ "OPOL_F",
    care1_l1=="regularly" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") &care2_l2=="regularly"~ "OPOL_F",
    care1_l1=="sometimes" & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "OPOL_F",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2=="sometimes"~ "OPOL_F",
    
    
  #one-parent-bilingual: One parent speaks 2 languages, the other parent only speaks one language
    
    #Starting point
    care1_l1== "regularly" & care1_l2=="regularly" & care2_l1 == "regularly" & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1== "regularly" & care1_l2=="regularly" & care2_l1 %in% c("never", "NA") & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1== "regularly" & care1_l2 %in% c("never", "NA") & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",

    #Some bilingual parents put both of their languages as sometimes rather than both as regularly
    care1_l1== "sometimes" & care1_l2=="sometimes" & care2_l1 == "regularly" & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1== "sometimes" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1== "regularly" & care1_l2 %in% c("never", "NA") & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",

    #One parent bilingual (R&R or S&S) and another parent that speaks one of the language but not the other (R|S & N|NA)
    care1_l1 == "regularly" & care1_l2=="regularly" & care2_l1 %in% c("regularly", "sometimes") & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1 == "regularly" & care1_l2=="regularly" & care2_l1 %in% c("never", "NA") & care2_l2 %in% c("regularly", "sometimes") ~ "one-parent-bilingual",
    care1_l1 %in% c("regularly", "sometimes") & care1_l2 %in% c("never", "NA") & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2 %in% c("regularly", "sometimes") & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",

    care1_l1 == "sometimes" & care1_l2=="sometimes" & care2_l1 %in% c("regularly", "sometimes") & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1 == "sometimes" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") & care2_l2 %in% c("regularly", "sometimes") ~ "one-parent-bilingual",
    care1_l1 %in% c("regularly", "sometimes") & care1_l2 %in% c("never", "NA") & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2 %in% c("regularly", "sometimes") & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    
    #Both parents speak the same language regularly, and one of them speak another language sometimes 
    #(not one-parent-one-lang-flex because both parents use the same language regularly in opposition to each parent having a different language that they use regularly)
    care1_l1=="regularly" & care1_l2=="sometimes" & care2_l1=="regularly" & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="regularly" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    care1_l1=="sometimes" & care1_l2=="regularly" & care2_l1 %in% c("never", "NA")& care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="sometimes" & care2_l2=="regularly" ~ "one-parent-bilingual",
    
    
  #both-parents-bilingual: Both parents speak both languages either regularly or sometimes
    care1_l1%in% c("regularly", "sometimes") & care1_l2%in% c("regularly", "sometimes") & care2_l1%in% c("regularly", "sometimes") &care2_l2%in% c("regularly", "sometimes") ~ "both-parents-bilingual",

  #one-parent-one-lang-flex: Each parent speaks mainly one language, and one of them sometimes speaks another language
  #The same language cannot be spoken regularly by both parents or it comes to be filled under the one-parent-bilingual strategy.
  #**NOTE: we ended up having a single category for OPOL instead of divinding it into strict and flex.
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="sometimes" &care2_l2=="regularly"~ "one-parent-one-lang",
    care1_l1=="regularly" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") &care2_l2=="regularly"~ "one-parent-one-lang",
    care1_l1=="sometimes" & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "one-parent-one-lang",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2=="sometimes"~ "one-parent-one-lang",
    
  #one-language-at-home: There is only one language spoken in the home by both parents
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "one-language-at-home",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1 %in% c("never", "NA") & care2_l2=="regularly"~ "one-language-at-home",
    
    care1_l1=="sometimes" & care1_l2 %in% c("never", "NA") & care2_l1=="sometimes" &care2_l2 %in% c("never", "NA")~ "one-language-at-home",
    care1_l1 %in% c("never", "NA") & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") & care2_l2=="sometimes"~ "one-language-at-home",
    
  #single-parent: Family in which there is only one caregiver
    care1_l1 %in% c("never", "NA") & care1_l2 %in% c("never", "NA") & care1_l3 %in% c("never", "NA") & care1_l4 %in% c("never", "NA") ~ "single-parent",
    care2_l1 %in% c("never", "NA") & care2_l2 %in% c("never", "NA") & care2_l3 %in% c("never", "NA") & care2_l4 %in% c("never", "NA") ~ "single-parent"
  
    ))
    

final_data_strat_2opol <-
  final_data_strat_2opol %>%
  mutate(bilinugal_strategy= case_when(strategy=="one-language-at-home" & childcare_l1 == l1 & childcare_l2 %in% c(NA, "NA")  ~ "no",
                                       strategy=="one-language-at-home" & childcare_l2 == l1 & childcare_l1 %in% c(NA, "NA") ~"no",
                                       strategy=="one-language-at-home" & childcare_l1 %in% c(NA, "NA") & childcare_l2 %in% c(NA, "NA") ~"no",
                                       TRUE~"yes")) %>%
  filter(bilinugal_strategy=="yes")

final_data_strat_2opol <- 
  final_data_strat_2opol %>%
  filter(exp_l1 <95) %>%
  filter(exp_l2 >5)


#Calculate the proportion for the different strategies
prop_strategy_2opol<-final_data_strat_2opol%>%
group_by(strategy) %>%
  tally() %>%
  mutate(prop = n/sum(n))

```

