---
title: "2_main_analyses"
author: "ASM"
date: "26/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(dplyr)
library(lme4)
library(lmerTest)
library(rstatix)
```


#----1. load clean data
```{r}

load(here("anonymized_data/final_merged_data.Rda"))
```


#----2. explore demographics
```{r}

n<- final_data%>%
  distinct(unique_id) #n of 552

gender<- final_data %>%
  distinct(unique_id, gender)%>%
  group_by(gender)%>%
  tally()
#16 na for gender I think from LEQs withouth associated demographics

range(final_data$age, na.rm = T) #4.33 - 30.9 months so 4 - 31 if we round.
```



#-----3. categorize LEQ data into family language strategies
```{r}
final_data_strat <- final_data %>%
  mutate(strategy=case_when(
    
  #one-parent-one-lang-strict: Each parent speaks only one language and both parents don't speak the same language
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1 %in% c("never", "NA") & care2_l2=="regularly"~ "one-parent-one-lang-strict",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "one-parent-one-lang-strict",
    
  #one-parent-one-lang-flex: Each parent speaks mainly one language, and one of them sometimes speaks another language
  #(The same language cannot be spoken regularly by both parents or that would be considered a one-parent-bilingual strategy)
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="sometimes" &care2_l2=="regularly"~ "one-parent-one-lang-flex",
    care1_l1=="regularly" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") &care2_l2=="regularly"~ "one-parent-one-lang-flex",
    care1_l1=="sometimes" & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "one-parent-one-lang-flex",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2=="sometimes"~ "one-parent-one-lang-flex",
    
    
  #one-parent-bilingual: One parent speaks 2 languages, the other parent only speaks one language
    
    #Starting point
    care1_l1== "regularly" & care1_l2=="regularly" & care2_l1 == "regularly" & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1== "regularly" & care1_l2=="regularly" & care2_l1 %in% c("never", "NA") & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1== "regularly" & care1_l2 %in% c("never", "NA") & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",

    #Some bilingual parents put both of their languages as sometimes rather than both as regularly
    care1_l1== "sometimes" & care1_l2=="sometimes" & care2_l1 == "regularly" & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1== "sometimes" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1== "regularly" & care1_l2 %in% c("never", "NA") & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",

    #One parent bilingual (R&R or S&S) and another parent that speaks one of the language but not the other (R|S & N|NA)
    care1_l1 == "regularly" & care1_l2=="regularly" & care2_l1 %in% c("regularly", "sometimes") & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1 == "regularly" & care1_l2=="regularly" & care2_l1 %in% c("never", "NA") & care2_l2 %in% c("regularly", "sometimes") ~ "one-parent-bilingual",
    care1_l1 %in% c("regularly", "sometimes") & care1_l2 %in% c("never", "NA") & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2 %in% c("regularly", "sometimes") & care2_l1 == "regularly" & care2_l2=="regularly" ~ "one-parent-bilingual",

    care1_l1 == "sometimes" & care1_l2=="sometimes" & care2_l1 %in% c("regularly", "sometimes") & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1 == "sometimes" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") & care2_l2 %in% c("regularly", "sometimes") ~ "one-parent-bilingual",
    care1_l1 %in% c("regularly", "sometimes") & care1_l2 %in% c("never", "NA") & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2 %in% c("regularly", "sometimes") & care2_l1 == "sometimes" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    
    #Both parents speak the same language regularly, and one of them speak another language sometimes 
    #(not one-parent-one-lang-flex because both parents use the same language regularly in opposition to each parent having a different language that they use regularly)
    care1_l1=="regularly" & care1_l2=="sometimes" & care2_l1=="regularly" & care2_l2 %in% c("never", "NA") ~ "one-parent-bilingual",
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="regularly" & care2_l2=="sometimes" ~ "one-parent-bilingual",
    care1_l1=="sometimes" & care1_l2=="regularly" & care2_l1 %in% c("never", "NA")& care2_l2=="regularly" ~ "one-parent-bilingual",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="sometimes" & care2_l2=="regularly" ~ "one-parent-bilingual",
    
    
  #both-parents-bilingual: Both parents speak both languages either regularly or sometimes
    care1_l1%in% c("regularly", "sometimes") & care1_l2%in% c("regularly", "sometimes") & care2_l1%in% c("regularly", "sometimes") &care2_l2%in% c("regularly", "sometimes") ~ "both-parents-bilingual",

  #one-parent-one-lang-flex: Each parent speaks mainly one language, and one of them sometimes speaks another language
  #The same language cannot be spoken regularly by both parents or it comes to be filled under the one-parent-bilingual strategy
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="sometimes" &care2_l2=="regularly"~ "one-parent-one-lang-flex",
    care1_l1=="regularly" & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") &care2_l2=="regularly"~ "one-parent-one-lang-flex",
    care1_l1=="sometimes" & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "one-parent-one-lang-flex",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1=="regularly" &care2_l2=="sometimes"~ "one-parent-one-lang-flex",
    
  #one-language-at-home: There is only one language spoken in the home by both parents
    care1_l1=="regularly" & care1_l2 %in% c("never", "NA") & care2_l1=="regularly" &care2_l2 %in% c("never", "NA")~ "one-language-at-home",
    care1_l1 %in% c("never", "NA") & care1_l2=="regularly" & care2_l1 %in% c("never", "NA") & care2_l2=="regularly"~ "one-language-at-home",
    
    care1_l1=="sometimes" & care1_l2 %in% c("never", "NA") & care2_l1=="sometimes" &care2_l2 %in% c("never", "NA")~ "one-language-at-home",
    care1_l1 %in% c("never", "NA") & care1_l2=="sometimes" & care2_l1 %in% c("never", "NA") & care2_l2=="sometimes"~ "one-language-at-home",
    
  #single-parent: Family in which there is only one caregiver
    care1_l1 %in% c("never", "NA") & care1_l2 %in% c("never", "NA") & care1_l3 %in% c("never", "NA") & care1_l4 %in% c("never", "NA") ~ "single-parent",
    care2_l1 %in% c("never", "NA") & care2_l2 %in% c("never", "NA") & care2_l3 %in% c("never", "NA") & care2_l4 %in% c("never", "NA") ~ "single-parent"
  
    ))
    

#Calculate the proportion for the different strategies
prop_strategy<-final_data_strat%>%
group_by(strategy) %>%
  tally() %>%
  mutate(prop = n/sum(n))

#save(final_data_strat, file=here("anonymized_data/final_data_strat.Rda"))

```

#---- coding minority versus majority language
```{r}

final_data_strat <- final_data_strat %>% 
  mutate(lang_status = case_when(
    l2=="NA" ~ "monolingual",
    exp_l2== 0 ~ "monolingual",
    l1 %in% c("French", "English") & l2 %in% c("French", "English") ~ "maj",
    TRUE ~ "min"
  ))

```

#------ getting french language exposure

```{r}

final_data_strat <- final_data_strat %>%
  mutate(fre_exp = case_when(l1 == "French" ~ exp_l1,
                             l2 == "French"~ exp_l2,
                             TRUE ~ 0)) # if it is not l1 or 2 the exposure is less than 10, I can't get it somehow. Will try to figure out.

```


#-------- goodness of fit cat analyses
```{r}


```


#--------- linear mixed models
```{r}

m1 <- lmer(exp_l1 ~ strategy + (1|anon_baby_id), data=final_data_strat) #can't with unique id, just anon. To check?

summary(m1)
#some significant effects by strategy.
#quite a bit of variance from the by-subject random intercept = balacedeness has to do also with individual variability than langauge strategy.
#take out the single parent language
#Maybe collapse the OPOL groups?

m1.1 <- lmer(exp_l1 ~ strategy + lang_status + (1|anon_baby_id), data=final_data_strat) 
summary(m1.1)
#L1 is many language code everything relative to French as the official language. 

m1.2 <- lmer(exp_l1 ~ strategy * lang_status + (1|anon_baby_id), data=final_data_strat) 
summary(m1.2)


anova(m1, m1.1) #significantly different so langauge status matters but is it due to the monolinguals?

test<- lmer(exp_l1 ~ lang_status + (1|anon_baby_id), data=final_data_strat) 
summary(test) #maybe monolinguals are driving the effect. Which makes sense because ofc monolinguals are unbalanced.


#prediction of French exposure
m2 <- lmer(fre_exp ~ strategy + (1|anon_baby_id), data=final_data_strat) 
m2.2<- lmer(fre_exp ~ strategy * lang_status + (1|anon_baby_id), data=final_data_strat) 
summary(m2.2)
summary(m2)
#Both parents bilingual and opol-strict marginally

#Look at heritage language speakers and look at the french exposure. 
#visualization more similar to analyses. Mean l1 exposure by strategy l1 exp in y.
#Do we just want to do t-tests instead .. order the strategies by how much l1 exposure they give you. And then heritage vs non heritage.

```


#T-test pairwise comparisons
```{r}
for_t_tests<- final_data_strat %>%
  select(c(strategy, lang_status, fre_exp, exp_l1)) 

#Order l1 amount of exposure by strategy
l1_by_strategy <- for_t_tests %>%
  select(c(strategy, exp_l1)) %>%
  group_by(strategy) %>%
  summarise(mean(exp_l1))

#French exposure
fre_by_strategy <- for_t_tests %>%
  select(c(strategy, fre_exp)) %>%
  group_by(strategy) %>%
  summarise(mean(fre_exp))

#Pairwise t test comparisons for all the strategies against amount of l1 exposure. Bonferroni corrected p for multiple comparisons. 
pwc_exp_l1 <- for_t_tests %>% 
  pairwise_t_test(
    exp_l1~strategy, pool.sd = FALSE,
    p.adjust.method = "bonferroni"
    )
pwc_exp_l1

#Pairwise t test comparisons for all the strategies against amount of french exposure. Bonferroni corrected p for multiple comparisons.
pwc_fre_exp <- for_t_tests %>% 
  pairwise_t_test(
    fre_exp~strategy, pool.sd = FALSE,
    p.adjust.method = "bonferroni"
    )
pwc_fre_exp




#langauge status
t.test(fre_exp~lang_status, data = for_t_tests, subset = lang_status %in% c("maj","min"),  mu=0, conf.level = 0.95, paired=F) #If you speak a majority langauge you are more likely to have more fre exp

#non Heritage englissh and french, vs.heritage. 


t.test(exp_l1~lang_status, data = for_t_tests, subset = lang_status %in% c("maj","min"),  mu=0, conf.level = 0.95, paired=F) #weather the langauges you speak at home are majority or minority does not influence the amount of L1 you get


```


#---------- create and save longitudinal data frame
```{r}
#keeps only data where the baby participated more than once
longitudinal_data<- final_data_strat %>%
  add_count(anon_baby_id) %>%
  filter(nn>1)

save(longitudinal_data, file=here("anonymized_data/longitudinal_data.Rda"))
```

