---
title: "results_markdown"
author: "ASM"
date: "13/01/2023 last updated 01/05/2023"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 100, digits = 4)
```


## Data call in, and methods participant information

```{r data call in, include=FALSE}
library(lubridate)
library(sparkline)
library(webshot)
library(htmlwidgets)
library(formattable)
library(here)
library(lme4)
library(lmerTest)
library(rstatix)
library(papeR)
library(knitr)
library(waffle)
library(ggsankey)
library(dplyr)
library(tidyverse)
library(patchwork)
library(ggpubr)
library(broom)
library(janitor)
library(glmmTMB)
library(DHARMa)
library(betareg)
library(emmeans)
library(ggiraphExtra)
library(ggeffects)
library(mvtnorm)
library(boot)
library(bbmle)
library(performance)
library(see)
library(writexl)
library(ggtext)
library(kableExtra)


load(here("anonymized_data/final_merged_data.Rda"))
load(here("anonymized_data/final_data_no_exc.Rda"))
load(here("anonymized_data/final_data_strat.Rda"))
load(here("anonymized_data/longitudinal_data.Rda"))

SES_info<- readxl::read_xlsx("anonymized_data/SES_and_ethicity_info.xlsx")
SES_info<-clean_names(SES_info)



#Saving my palette to use in visualizations
my_yellow<-"#FFC107"
my_orange<- "#D95F02"
my_blue<- "#1F78B4"
my_green<- "#33a02c"
my_purple<- "#683f6d"

```


```{r participants information, include=FALSE}
#### CONSTRUCTING AND DESCRIBING ALL RELEVANT DATA SETS ####

#Trilingul exclusions count
total_excluded_triling<- final_data_no_exc %>%
    group_by(unique_id, exp_l1, exp_l2)%>%
   mutate(total_l1_l2_exp=(sum(exp_l1,exp_l2,na.rm = T))) %>%
  ungroup() %>%
  filter(total_l1_l2_exp<=90) %>%
  distinct(unique_id)%>%
  tally()

#Monolingual exclusions
total_monoling_excluded<- final_data_no_exc %>%
  filter(exp_l1 >95) %>%
  filter(exp_l2 <5) %>%
  distinct(unique_id) %>%
  tally()


#after third language exclusions exclusions
n <- final_data_strat %>%
  distinct(unique_id) %>%
  tally()

#subseting to get data only from each child's first visit to the lab. For main analyses
first_visit_only <- final_data_strat%>%
    arrange(anon_baby_id, age) %>%
  group_by(anon_baby_id) %>%
  mutate(visit = row_number()) %>%
  ungroup() %>%
  filter(visit==1) 

#n when only taking first visit
n_keep_first_visit<-first_visit_only %>%
  distinct(anon_baby_id)%>%
  tally()

age_min <- round(min(first_visit_only$age, na.rm = T), 2)
age_max<- round(max(first_visit_only$age, na.rm = T), 2)
age_mean<- round(mean(first_visit_only$age, na.rm = T), 2)
age_sd<- round(sd(first_visit_only$age, na.rm = T), 2)

female<- first_visit_only %>%
  filter(gender=="female")%>%
  distinct(anon_baby_id)%>% #using anon_baby_id since it uniquely identifies individual babies, instead of identifying by study
  tally()

num_visits <- final_data_strat %>% 
  count(anon_baby_id, name = "n_visits") %>% 
  count(n_visits, name = "n_families")  %>% 
  mutate(n_data_points = n_families* n_visits)


#French-English-Heritage bilingual percentages

#### JOINING SES INFO TO CLEAN DATA
## Make sure 5718960_cogmisp24 6517080_segment8 have the right languages on the SES sheet

first_visit_only<- first_visit_only %>%
  right_join(SES_info, first_visit_only, by=c("study","unique_id", "anon_baby_id", "l1", "l2"))

FEH <- first_visit_only %>%
  mutate(l1 = case_when(l1=="French" ~ "French",
                        l1=="English" ~ "English",
                        TRUE ~ "Heritage")) %>%
    mutate(l2 = case_when(l2=="French" ~ "French",
                        l2=="English" ~ "English",
                        TRUE ~ "Heritage")) %>%
  mutate(bilingual_type = case_when(l1 %in% c("French", "English") & l2 %in% c("French", "English") ~ "fre-eng",
                                    l1 %in% c("French", "Heritage") & l2 %in% c("French", "Heritage") ~ "fre-her",
                                    l1 %in% c("Heritage", "English") & l2 %in% c("Heritage", "English") ~ "eng-her")) 



#Exporting the final data set that we used in all analyses and visualizations
#write_xlsx(FEH,"anonymized_data\\fam_Str_cross_sectional.xlsx")
  
FEH_prof<- FEH %>%
  mutate(mother_french_aoa = case_when (l1 == "French" ~ age_l1_acquired_mother,
                                      l1 %in% c("English","Heritage")~ age_l2_acquired_mother)) %>%
 mutate(mother_english_aoa = case_when (l1 == "English" ~ age_l1_acquired_mother,
                                      l1%in% c("French","Heritage")~ age_l2_acquired_mother)) %>%
   mutate(mother_heritage_aoa = case_when (l1 == "Heritage" ~ age_l1_acquired_mother,
                                      l1%in% c("French","English")~ age_l2_acquired_mother)) %>%
  mutate(father_french_aoa = case_when (l1 == "French" ~ age_l1_acquired_father,
                                      l1 %in% c("English","Heritage")~ age_l2_acquired_father)) %>%
 mutate(father_english_aoa = case_when (l1 == "English" ~ age_l1_acquired_father,
                                      l1%in% c("French","Heritage")~ age_l2_acquired_father)) %>%
     mutate(father_heritage_aoa = case_when (l1 == "Heritage" ~ age_l1_acquired_father,
                                      l1%in% c("French","English")~ age_l2_acquired_father)) %>%
  mutate(mother_french_aoa = case_when(mother_french_aoa <= 5 ~ "early_acquisition",
                                       mother_french_aoa >5 ~ "older_than_5",
                                       is.na(mother_french_aoa)~ NA)) %>%
    mutate(mother_english_aoa = case_when(mother_english_aoa <= 5 ~ "early_acquisition",
                                       mother_english_aoa >5 ~ "older_than_5",
                                      is.na(mother_english_aoa) ~ NA)) %>%
    mutate(mother_heritage_aoa = case_when(mother_heritage_aoa <= 5 ~ "early_acquisition",
                                       mother_heritage_aoa >5 ~ "older_than_5",
                                        is.na(mother_heritage_aoa)~ NA)) %>%
    mutate(father_french_aoa = case_when(father_french_aoa <= 5 ~ "early_acquisition",
                                       father_french_aoa >5 ~ "older_than_5",
                                        is.na(father_french_aoa)~ NA)) %>%
      mutate(father_english_aoa = case_when(father_english_aoa <= 5 ~ "early_acquisition",
                                       father_english_aoa >5 ~ "older_than_5",
                                        is.na(father_english_aoa)~ NA)) %>%
        mutate(father_heritage_aoa = case_when(father_heritage_aoa <= 5 ~ "early_acquisition",
                                       father_heritage_aoa >5 ~ "older_than_5",
                                        is.na(father_english_aoa)~ NA)) 
  
  
  



## Mothers proficiency distribution
   mothers_fre_prof <- FEH_prof%>%
     group_by(mother_french_aoa)%>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100) %>% 
     ungroup() 
   
    mothers_eng_prof <- FEH_prof%>%
     group_by(mother_english_aoa)%>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100) %>% 
     ungroup() 
    
    mothers_her_prof <- FEH_prof%>%
     group_by(mother_heritage_aoa)%>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100) %>% 
     ungroup() 
     
   #Fathers proficiency distribution

     fathers_fre_prof <- FEH_prof%>%
     group_by(father_french_aoa)%>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100) %>% 
     ungroup() 
   
    fathers_eng_prof <- FEH_prof%>%
     group_by(father_english_aoa)%>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100) %>% 
     ungroup() 
    
    fathers_her_prof <- FEH_prof%>%
     group_by(father_heritage_aoa)%>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100) %>% 
     ungroup()   
    


FEH_perc<- FEH %>%
  group_by(bilingual_type) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)


#By bilingual type percentages

fre_eng_perc <- FEH %>%
  filter(bilingual_type== "fre-eng")%>%
 group_by(l1) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)
  
  
  fre_her_perc <- FEH %>%
  filter(bilingual_type=="fre-her")%>%
  group_by(l1) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

  
  her_eng_perc <- FEH %>%
  filter(bilingual_type=="eng-her") %>%
  group_by(l1) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

#l1 amount of exposure range
min_exp_range <- final_data_strat %>% 
  select(exp_l1) %>%
  min()

max_exp_range <-final_data_strat %>% 
  select(exp_l1) %>%
  max()


## Calculate percentages of overall maternal education by strategy for supplementary materials
library(RColorBrewer)

 FE_maternal_education <- FEH %>%
  filter(bilingual_type=="fre-eng") %>%
   filter(!strategy == "single-parent")%>%
   drop_na(strategy)%>%
  group_by(strategy, maternal_education) %>%
   drop_na(maternal_education)%>%
 mutate(maternal_education = case_when(maternal_education %in% c("highschool", "less_than_highschool")~"highschool or less",
                                         maternal_education %in% c("cgep", "university", "trade_school_diploma", "professional_degree") ~ "post-secondary education",
                                        maternal_education %in% c("masters", "more_than_masters")~"post-graduate education")) %>%
 
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)
 
 FE_maternal_education$maternal_education <- factor(FE_maternal_education$maternal_education, levels= c("post-graduate education", "post-secondary education", "highschool or less"))
 
 sup_figure_1<- ggplot(FE_maternal_education, aes(y=perc, x=strategy, fill=maternal_education)) +
   geom_col(position = "fill") +
   scale_fill_brewer(palette="Dark2")+
   labs(title= "French-English sample maternal education by strategy")+
   theme(axis.text.x = element_text(angle = 25))
 
 
  HER_maternal_education <- FEH %>%
  filter(bilingual_type %in% c("fre-her", "eng-her")) %>%
       filter(!strategy == "single-parent")%>%
   drop_na(strategy)%>%
  group_by(strategy, maternal_education) %>%
   drop_na(maternal_education) %>%
 mutate(maternal_education = case_when(maternal_education %in% c("highschool", "less_than_highschool")~"highschool or less",
                                         maternal_education %in% c("cgep", "university", "trade_school_diploma", "professional_degree") ~ "post-secondary education",
                                        maternal_education %in% c("masters", "more_than_masters")~"post-graduate education")) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)
  
   HER_maternal_education$maternal_education <- factor(HER_maternal_education$maternal_education, levels=c("post-graduate education", "post-secondary education", "highschool or less"))
 
 sup_figure_2<- ggplot(HER_maternal_education, aes(y=perc, x=strategy, fill=maternal_education)) +
   geom_col(position = "fill") +
   scale_fill_brewer(palette="Dark2") +
   labs(title= "Heritage sample maternal education by strategy")+
   theme(axis.text.x = element_text(angle = 25))
 
 
 
  FE_paternal_education <- FEH %>%
      filter(bilingual_type=="fre-eng") %>%
       filter(!strategy == "single-parent")%>%
   drop_na(strategy)%>%
  group_by(strategy, paternal_education) %>%
   drop_na(paternal_education) %>%
     mutate(paternal_education = case_when(paternal_education %in% c("highschool", "less_than_highschool")~"highschool or less",
                                         paternal_education %in% c("cgep", "university", "trade_school_diploma", "professional_degree") ~ "post-secondary education",
                                        paternal_education %in% c("masters", "more_than_masters")~"post-graduate education")) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)
  
     FE_paternal_education$paternal_education <- factor(FE_paternal_education$paternal_education, levels=c("post-graduate education", "post-secondary education", "highschool or less"))
  
  sup_figure_3<- ggplot(FE_paternal_education, aes(y=perc, x=strategy, fill=paternal_education)) +
   geom_col(position = "fill")  +
    scale_fill_brewer(palette="Dark2") +
   labs(title= "French-English sample paternal education by strategy")+
   theme(axis.text.x = element_text(angle = 25))
  
   HER_paternal_education <- FEH %>%
  filter(bilingual_type %in% c("fre-her", "eng-her")) %>%
       filter(!strategy == "single-parent")%>%
  group_by(strategy, paternal_education) %>%
   drop_na(paternal_education) %>%
          mutate(paternal_education = case_when(paternal_education %in% c("highschool", "less_than_highschool")~"highschool or less",
                                         paternal_education %in% c("cgep", "university", "trade_school_diploma", "professional_degree") ~ "post-secondary education",
                                        paternal_education %in% c("masters", "more_than_masters")~"post-graduate education")) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)
   
        HER_paternal_education$paternal_education <- factor(HER_paternal_education$paternal_education, levels=c("post-graduate education", "post-secondary education", "highschool or less"))
  
  sup_figure_4<- ggplot(HER_paternal_education, aes(y=perc, x=strategy, fill=paternal_education)) +
   geom_col(position = "fill")+
    scale_fill_brewer(palette="Dark2") +
   labs(title= "Heritage sample paternal education by strategy")+
   theme(axis.text.x = element_text(angle = 25))
 
  #No graphs for this one as there are too many categories
   FE_ethnicity <- FEH %>%
     filter(bilingual_type=="fre-eng")%>%
  group_by(strategy, child_ethnicity) %>%
   drop_na(child_ethnicity) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100) 
  
   
   
######## SES and ethnicity stats not by strategy   
   
##MATERNAL EDUCATION French-English sample
 FE_maternal_education <- FEH %>%
  filter(bilingual_type=="fre-eng") %>%
  group_by(maternal_education) %>%
   drop_na(maternal_education) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)
 
 ##Paternal EDUCATION French-English sample
 FE_paternal_education <- FEH %>%
  filter(bilingual_type=="fre-eng") %>%
  group_by(paternal_education) %>%
   drop_na(paternal_education) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

 ##Child ethnicity French-English sample
  FE_child_ethicity <- FEH %>%
  filter(bilingual_type=="fre-eng") %>%
  group_by(child_ethnicity) %>%
    drop_na(child_ethnicity)%>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

  
  ##MATERNAL EDUCATION heritage sample
 her_maternal_education <- FEH %>%
  filter(!bilingual_type=="fre-eng") %>%
  group_by(maternal_education) %>%
   drop_na(maternal_education) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)
 
 ##Paternal EDUCATION heritage sample
 her_paternal_education <- FEH %>%
  filter(!bilingual_type=="fre-eng") %>%
  group_by(paternal_education) %>%
  drop_na(paternal_education) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

 ##Child ethnicity her sample
  her_child_ethicity <- FEH %>%
  filter(!bilingual_type=="fre-eng") %>%
  group_by(child_ethnicity) %>%
    drop_na(child_ethnicity) %>%
  tally()%>%
    mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)
  
  
  
  
#Prepping longitudinal data excluding irrelevant cases


longitudinal_data_analyses <- longitudinal_data %>% 
  arrange(anon_baby_id, age) %>%
  group_by(anon_baby_id) %>%
  mutate(visit = row_number()) %>%
  ungroup() %>% 
  mutate(first_visit_date = case_when(visit == 1 ~ leq_date)) %>%
  mutate(second_visit_date = case_when(visit == 2 ~ leq_date)) %>%
  group_by(anon_baby_id) %>%
  fill(first_visit_date, second_visit_date, .direction="updown") %>% #to collapse the rows and be able to calculate visit
  ungroup() %>%
  mutate(length_between_visits = abs(interval(start= first_visit_date, end=second_visit_date)/ duration (n=1, unit="days" ))) %>%
  filter(! length_between_visits < 15) %>%
  mutate(l1 = case_when(l1=="French" ~ "French",
                        l1=="English" ~ "English",
                        TRUE ~ "Heritage")) %>%
    mutate(l2 = case_when(l2=="French" ~ "French",
                        l2=="English" ~ "English",
                        TRUE ~ "Heritage")) %>%
  mutate(bilingual_type = case_when(l1 %in% c("French", "English") & l2 %in% c("French", "English") ~ "fre-eng",
                                    l1 %in% c("French", "Heritage") & l2 %in% c("French", "Heritage") ~ "fre-her",
                                    l1 %in% c("Heritage", "English") & l2 %in% c("Heritage", "English") ~ "eng-her")) 

#Longitudinal data set n
n_long <-longitudinal_data_analyses %>% 
  distinct(unique_id)%>%
  tally()

#Longitudinal data set length between visit one and 2
visit_length <- longitudinal_data_analyses %>% 
  filter(visit <= 2)
  

avg_visit_l <- round(mean(visit_length$length_between_visits), 2)
min_visit_l <- round(min(visit_length$length_between_visits),2)
max_visit_l <- round(max(visit_length$length_between_visits),2)
sd_visit_l <- round(sd(visit_length$length_between_visits),2)
```

 
```{r}
kable(FE_ethnicity)
```

## Study 1: French-English data analyses

```{r Study 1: proportion of strategy use visualizations, include=FALSE}
#Family language strategy visualization

####### FOR THE FRENCH- ENGLISH SAMPLE ############

#Calculating how many families use each strategy and its corresponding %
prop_strategy_FE<- FEH %>%
  filter(bilingual_type == "fre-eng")%>%
group_by(strategy) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

#Reordering levels so legend in the graph is in order.
prop_strategy_FE$strategy<- factor(prop_strategy_FE$strategy, levels= c("both-parents-bilingual", "one-parent-bilingual", "one-parent-one-lang", "one-language-at-home", "single-parent"))

prop_strategy_FE<- prop_strategy_FE %>%
 arrange(desc(prop))


#Waffle plot
V1_FE<- setNames(prop_strategy_FE$n, c("both-parents-bilingual", "one-parent-bilingual", "one-parent-one-lanaguage", "one-language-at-home", "single-parent"))

figure_1<- waffle(parts = V1_FE, rows=13, colors = c(my_orange, my_yellow, my_blue, my_green, my_purple), keep = T, size=0.6)+
    annotate("richtext", x=c(4,11,15), y=8, label=c("114", "54", "41"), size=10) +
  annotate("richtext", x=17, y=6, label= "7", size=10)+
  annotate("richtext", x=17, y=10, label= "5", size=10)+
 theme(legend.text= element_text(size=18),legend.title= element_text(size=18)) 

ggsave(file="Figure_1.png", width=25, height=7, dpi=300)


#Making a figure of most used strategies divided by lang exposure
for_breakdown <- first_visit_only %>%
  mutate(l1 = case_when(l1=="French" ~ "French",
                        l1=="English" ~ "English",
                        TRUE ~ "Heritage")) %>%
group_by(strategy, l1) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

for_breakdown$strategy<- factor(for_breakdown$strategy, levels= c("both-parents-bilingual", "one-parent-bilingual", "one-parent-one-lang", "one-language-at-home", "single-parent"))

ggplot(for_breakdown, aes(x=l1, y=n, fill=strategy)) + 
  geom_bar(stat="identity", position="fill") +
  scale_fill_manual (name = "Family Strategy", values =c(my_orange, my_yellow, my_blue, "#91bfdb", "#e0f3f8"))

```



```{r Study 1: Goodness of fit analysis, include=FALSE}

for_chisq <- prop_strategy_FE %>%
  filter(!strategy %in% c("single-parent", "one-language-at-home")) 

xsq_test<- chisq.test(for_chisq$n)

chisq_value<- round(xsq_test$statistic, 2)
chisq_p<- round(xsq_test$p.value, 4)

```


```{r Study 1: Mother and father language exploration, include=FALSE}

### Looking at the individual parent strategies in each family language strategy

##Both parents bilingual
FE_both_parent_b<- FEH %>%
  filter(type_of_family == "mother-father family") %>%
  filter(bilingual_type == "fre-eng") %>%
  filter(strategy=="both-parents-bilingual") %>%
  mutate(caregiver1_French =  case_when (l1== "French"~care1_l1,
                                         l1== "English"~care1_l2)) %>%
    mutate(caregiver1_English =  case_when (l1== "English"~care1_l1,
                                         l1== "French"~care1_l2)) %>%
    mutate(caregiver2_French =  case_when (l1== "French"~care2_l1,
                                         l1== "English"~care2_l2)) %>%
    mutate(caregiver2_English =  case_when (l1== "English"~care2_l1,
                                         l1== "French"~care2_l2)) %>%
  mutate(mom_use_strategy = case_when( caregiver1_French == "regularly" & caregiver1_English == "regularly" ~ "both regularly",
                                       caregiver1_French == "regularly" & caregiver1_English == "sometimes" ~ "french-reg-english-some",
                                       caregiver1_French == "sometimes" & caregiver1_English == "regularly" ~ "french-some-english-reg"))%>%
  mutate(dad_use_strategy = case_when( caregiver2_French == "regularly" & caregiver2_English == "regularly" ~ "both regularly",
                                       caregiver2_French == "regularly" & caregiver2_English == "sometimes" ~ "french-reg-english-some",
                                       caregiver2_French == "sometimes" & caregiver2_English == "regularly" ~ "french-some-english-reg",
                                       TRUE~"both-sometimes")) 

# what are the percentages ?
mom_biling_strat<- FE_both_parent_b %>%
  group_by(mom_use_strategy) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

dad_biling_strat<- FE_both_parent_b %>%
  group_by(dad_use_strategy) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)



## One-parent-bilingual

#Which parent is the bilingual parent?
FE_one_parent_b<- FEH %>%
    filter(type_of_family == "mother-father family") %>%
  filter(bilingual_type == "fre-eng") %>%
  filter(strategy=="one-parent-bilingual") %>%
    mutate(caregiver_biling = case_when(care1_l1 %in% c("regularly", "sometimes") & care1_l2 %in% c("regularly", "sometimes") ~ "caregiver1",
                                      TRUE ~ "caregiver2"))
#What are the percentages
FE_caregiver_bi_prop <- FE_one_parent_b %>%
    filter(type_of_family == "mother-father family") %>%
  group_by(caregiver_biling) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100) ## 81% mothers are the bilingual caregiver

#Which languages are spoken by the monolingual parent?

monoling_careg_lang<- FE_one_parent_b %>%
  mutate(monolingual_care_lang = case_when(caregiver_biling == "caregiver1" & care2_l1 %in% c("regularly", "sometimes") ~ l1,
                                           caregiver_biling == "caregiver1" & care2_l2 %in% c("regularly", "sometimes") ~ l2,
                                           caregiver_biling == "caregiver2" & care1_l1 %in% c("regularly", "sometimes") ~l1,
                                           caregiver_biling == "caregiver2" & care1_l2 %in% c("regularly", "sometimes") ~l2)) %>%
  group_by(monolingual_care_lang) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100) ## 69% on the parents who are monolingual speak English
                                    
  

##Also looking at OPOL to see who speaks French

FE_opol <- FEH %>%
    filter(type_of_family == "mother-father family") %>%
    filter(bilingual_type == "fre-eng") %>%
    filter(strategy=="one-parent-one-lang") %>% 
  mutate(momlangs = paste0(l1, care1_l1, "-", l2, care1_l2), #get mom languages and amount spoken
         dadlangs = paste0(l1, care2_l1, "-", l2, care2_l2)) %>% #get dad languages and amount spoken
  mutate(across(c(momlangs, dadlangs), 
                ~str_remove(., "-{0,1}.{6,7}never-{0,1}"))) %>% #remove the "never" languages
  mutate(across(c(momlangs, dadlangs), 
                ~case_when(str_detect(., "-") ~ "flex", #at this point, if there's still a hyphen, then both languages are used so it's "flex"
                           TRUE ~ str_remove(., "regularly|sometimes")))) %>% #if there is no hyphen, then it's just 1 language so remove the "regularly" or "sometimes" to just leave the language name
  mutate(parents_lang_use = case_when(dadlangs == "flex" ~ paste0("dad_", str_to_lower(dadlangs), "_mom_", str_to_lower(momlangs)),
                                        TRUE ~ paste0("mom_", str_to_lower(momlangs), "_dad_", str_to_lower(dadlangs)))) #if dad is the flex one, put him first, otherwise mom goes first


opol_count<- FE_opol %>%
  group_by(parents_lang_use) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

```


```{r Study 1: linear models analysis, include=FALSE}

FE_for_lms<- FEH %>%
  filter(bilingual_type == "fre-eng") %>%
  filter(!strategy == "single-parent") %>%
  filter(!strategy == "one-language-at-home") %>%
  mutate(strategy = case_when(strategy=="both-parents-bilingual"~"BothParentsBilingual",
                              strategy=="one-parent-bilingual"~"OneParentBilingual",
                              strategy=="one-parent-one-lang"~"OneParentOneLang"))

for_lms<- FE_for_lms %>% 
  select(gender, anon_baby_id, age, exp_l2, fre_exp, eng_exp, strategy, care1_l1, care1_l2, care2_l1, care2_l2, l1, l2, type_of_family) %>% 
  mutate(care1_l2 = case_when(care1_l2 =="NA" ~ "never",
                              TRUE ~ care1_l2)) %>%  #2023-07 going to need to fix this NAs in the cleaning script
    mutate(care2_l1 = case_when(care2_l1 =="NA" ~ "never",
                              TRUE ~ care2_l1)) %>%
      mutate(care2_l2 = case_when(care2_l2 =="NA" ~ "never",
                              TRUE ~ care2_l2)) %>%
  mutate(caregiver_1_french_use = case_when(l1=="French"~care1_l1,
                                            l2=="French"~care1_l2)) %>%
    mutate(caregiver_1_english_use = case_when(l1=="English"~care1_l1,
                                            l2=="English"~care1_l2)) %>%
    mutate(caregiver_2_french_use = case_when(l1=="French"~ care2_l1,
                                            l2=="French"~ care2_l2)) %>%
    mutate(caregiver_2_english_use = case_when(l1=="English"~care2_l1,
                                            l2=="English"~care2_l2)) %>%
  filter(gender != "NA") %>%
  filter(!strategy == "OneLanguageAtHome") %>%
  mutate(fre_exp = fre_exp/100, eng_exp = eng_exp/100, exp_l2 = exp_l2/100) %>%
  drop_na()

#STRATEGY LINEAR MODELS
lm_strat_eng<- lm(eng_exp ~ strategy, data=for_lms)
lm_strat_fre <- lm(fre_exp ~ strategy, data=for_lms)

#Summary of STRATEGY LINEAR models
summary(lm_strat_eng) #Slightly different, one parent bilingual is just a tad significant here and not for beta. 
summary(lm_strat_fre) #Same as above, one parent bilingual is significant and not for beta.


###### Careviver models 

  parents_for_lms <- for_lms%>%
     filter(type_of_family == "mother-father family") #Keeps only mother-father families as other configurations were to few to analyze separately

#MOTHER MODELS
lm_mom_eng<- lm(eng_exp ~ caregiver_1_english_use, data=for_lms)
lm_mom_fre<- lm(fre_exp ~ caregiver_1_french_use, data=for_lms)


#Summary of MOTHER models
summary(lm_mom_eng) #Similar pattern of results
summary(lm_mom_fre) #same pattern of results

#FATHER MODELS 
lm_dad_eng<- lm(eng_exp ~ caregiver_2_english_use, data=for_lms) 
lm_dad_fre<- lm(fre_exp ~ caregiver_2_french_use, data=for_lms)


#Summary of FATHER models
summary(lm_dad_eng) #Same pattern of results
summary(lm_dad_fre) #same pattern of results



#MOTHER AND FATHER MODELS
lm_parents_aditive_eng<- lm(eng_exp ~ caregiver_2_english_use + caregiver_1_english_use, data=parents_for_lms)
lm_parents_aditive_fre<- lm(fre_exp ~ caregiver_2_french_use + caregiver_1_french_use, data=parents_for_lms)


#Summary of Mother and Father models
summary(lm_parents_aditive_eng) #same pattern of results
summary(lm_parents_aditive_fre) #same pattern of results



performance::compare_performance(lm_parents_aditive_fre, lm_dad_fre, lm_mom_fre)
performance::compare_performance(lm_parents_aditive_eng, lm_dad_eng, lm_mom_eng)


##Comparison of strategy versus parents models
performance::compare_performance(lm_parents_aditive_fre, lm_strat_fre)
performance::compare_performance(lm_parents_aditive_eng, lm_strat_eng)





```


```{r Study 1: longitudinal analysis, include=FALSE}
## LONGITUDINAL DATA ANALYSES ##
FE_long_analyses<- longitudinal_data_analyses %>%
  filter(bilingual_type=="fre-eng") 


########### Count proportions ##########

v1_strat_prop <- FE_long_analyses %>%
  select(visit, strategy) %>%
  filter(visit==1) %>%
  filter(!strategy == "single-parent") %>%
  group_by(strategy) %>%
  tally(name = "n_first_visit")%>%
  mutate(proportion_first_visit = n_first_visit/sum(n_first_visit)) %>%
  mutate(percentage_first_visit= proportion_first_visit*100)


v2_strat_prop <- FE_long_analyses %>%
  select(visit, strategy) %>%
  filter(visit==2) %>%
  filter(!strategy == "single-parent") %>%
  group_by(strategy) %>%
  tally(name = "n_second_visit")%>% 
  mutate(proportion_second_visit = n_second_visit/sum(n_second_visit)) %>%
  mutate(percentage_second_visit= proportion_second_visit*100)

FE_percentages_visits <- merge(v1_strat_prop, v2_strat_prop, by="strategy")


###########################

###################### GLMER MODEL To learn weather changing strategy was related to the time between visits ########

FE_for_long_glmer<- FE_long_analyses %>%
  select(visit, strategy, length_between_visits, anon_baby_id) %>%
  filter(visit %in% c(1,2)) %>% 
  filter(!strategy == "single-parent") %>%
  pivot_wider(names_from = visit, values_from = strategy) %>%
  rename(time_1 = "1") %>%
  rename(time_2 = "2") %>%
  mutate(change_strat = case_when(time_1 == time_2 ~"no_change",
                                  TRUE~ "change")) 
  FE_for_long_glmer<- FE_for_long_glmer 
  

  FE_count_change <- FE_for_long_glmer %>%
      group_by(change_strat) %>%
  tally() %>%
  mutate(perc = (n/sum(n)*100))
  
  FE_strategy_change <- FE_for_long_glmer %>%
    filter(change_strat=="change") %>%
      group_by(time_2) %>%
  tally() %>%
  mutate(perc = (n/sum(n)*100))
  
long_model<- glmer(as.factor(change_strat) ~ scale(length_between_visits) +(1|anon_baby_id), data = FE_for_long_glmer, family="binomial")

summary(long_model)


############ make sankey graph ########

FE_for_sankey <- FE_for_long_glmer %>%
  select(-change_strat) %>%
    rename("time 1" = "time_1") %>%
  rename("time 2" = "time_2") %>%
  make_long("time 1", "time 2")  

FE_for_sankey <- FE_for_sankey %>%
  mutate(node= fct_relevel (node, "both-parents-bilingual", "one-parent-bilingual", "one-language-at-home", "one-parent-one-lang")) 




FE_p1<- ggplot(FE_for_sankey, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node), label=node )) +
  geom_sankey() 

FE_node_counts <- FE_for_sankey %>%
  filter(x=="time 1") %>%
  group_by(node) %>%
  summarise(count = n()) %>%
  ungroup()

FE_next_node_counts <- FE_for_sankey %>%
 filter(x=="time 1") %>%
  group_by(next_node) %>%
  summarise(count = n()) %>%
  ungroup()

FE_p1$data$node<- factor(FE_p1$data$node, levels= c("one-parent-one-lang","one-parent-bilingual", "both-parents-bilingual"))
FE_p1$data$next_node <- factor(FE_p1$data$next_node, levels= c("one-parent-one-lang","one-parent-bilingual", "both-parents-bilingual"))

figure_2 <- FE_p1+ 
      scale_fill_manual(name= "Family Language Strategies", values = c(my_blue, my_yellow, my_orange))


figure_2<- figure_2 +
 # geom_sankey_label(size=10, color="black", fill="white")+
  theme_bw()+
    annotate("richtext", x=c(1,1,1), y=c(12,-3,-15), label=FE_node_counts$count, size=10)+ #Adding the N at time 1
  annotate("richtext", x=c(2,2,2), y=c(12,-5,-15), label=FE_next_node_counts$count, size=10)+ #Adding the N at time 2
  theme(axis.text.x = element_text(size=35), axis.title = element_blank(), plot.title = element_text(size=35), axis.ticks = element_blank(), axis.text.y = element_blank(), legend.text = element_text(size=35), legend.title = element_text(size=35))


ggsave(file="Figure_2.png",  width=25, height=12, dpi=300)



##Mother sankey


mom_long<- FE_long_analyses %>% #this results in a dataframe that has one row per kid who had 2 FR-EN visits.
    filter(type_of_family == "mother-father family") %>%
  filter(!strategy=="single-parent") %>%
  filter(visit %in% c(1,2)) %>% 
  select(anon_baby_id, l1, l2, care1_l1, care1_l2, visit, length_between_visits) %>%
    mutate(caregiver_1_french_use = case_when(l1=="French"~care1_l1,
                                            l2=="French"~care1_l2)) %>%
    mutate(caregiver_1_english_use = case_when(l1=="English"~care1_l1,
                                            l2=="English"~care1_l2),
           visit = paste0("time_", visit)) %>%
  rename("Fre" = caregiver_1_french_use,
         "Eng" = caregiver_1_english_use) %>%
  select(-care1_l1, -care1_l2, -l1, -l2) %>%
  pivot_wider(names_from = visit, values_from = c(Fre, Eng)) %>%
  rename_at(vars(starts_with("Fre")), ~ paste0(str_remove(., "Fre_"), "_Fre")) %>%
  rename_at(vars(starts_with("Eng")), ~  paste0(str_remove(., "Eng_"), "_Eng")) %>%
  drop_na()

mom_long_french<- mom_long %>%
  select(anon_baby_id, length_between_visits, time_1_Fre, time_2_Fre)

mom_long_english<- mom_long %>%
  select(anon_baby_id, length_between_visits, time_1_Eng, time_2_Eng)

mom_long_fre_s <- mom_long_french %>%
      rename("time 1" = "time_1_Fre") %>%
  rename("time 2" = "time_2_Fre") %>%
  make_long("time 1","time 2") 

#Changeing the levels so that the graph is in order
mom_long_fre_s$node <- factor(mom_long_fre_s$node, levels= c("never","sometimes", "regularly"))
mom_long_fre_s$next_node <- factor(mom_long_fre_s$next_node, levels= c("never","sometimes","regularly"))

mom_long_eng_s <- mom_long_english %>%      
rename("time 1" = "time_1_Eng") %>%
  rename("time 2" = "time_2_Eng") %>%
  make_long("time 1","time 2") 

mom_long_eng_s$node <- factor(mom_long_eng_s$node, levels= c("never","sometimes", "regularly"))
mom_long_eng_s$next_node <- factor(mom_long_eng_s$next_node, levels= c("never","sometimes","regularly"))



v1_mother_prop_fre <- mom_long %>%
  select(time_1_Fre, time_1_Eng) %>%
  group_by(time_1_Fre) %>%
  tally(name = "n_first_visit")%>%
  mutate(proportion_first_visit = n_first_visit/sum(n_first_visit)) %>%
  mutate(percentage_first_visit= proportion_first_visit*100)

v2_mother_prop_fre <- mom_long %>%
  select(time_2_Fre, time_2_Eng) %>%
  group_by(time_2_Fre) %>%
  tally(name = "n_first_visit")%>%
  mutate(proportion_first_visit = n_first_visit/sum(n_first_visit)) %>%
  mutate(percentage_first_visit= proportion_first_visit*100)


v1_mother_prop_eng <- mom_long %>%
  select(time_1_Fre, time_1_Eng) %>%
  group_by(time_1_Eng) %>%
  tally(name = "n_first_visit")%>%
  mutate(proportion_first_visit = n_first_visit/sum(n_first_visit)) %>%
  mutate(percentage_first_visit= proportion_first_visit*100)

v2_mother_prop_eng <- mom_long %>%
  select(time_2_Fre, time_2_Eng) %>%
  group_by(time_2_Eng) %>%
  tally(name = "n_first_visit")%>%
  mutate(proportion_first_visit = n_first_visit/sum(n_first_visit)) %>%
  mutate(percentage_first_visit= proportion_first_visit*100)


mom_fre_node_counts <- mom_long_fre_s %>%
    filter(x=="time 1") %>%
  group_by(node) %>%
  summarise(count = n()) %>%
  ungroup()

mom_fre_next_node_counts <-  mom_long_fre_s %>%
 filter(x=="time 1") %>%
  group_by(next_node) %>%
  summarise(count = n()) %>%
  ungroup()


figure_3_a <- ggplot(mom_long_fre_s , aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node), label=node)) +
  geom_sankey(flow.color = "black") + 
  scale_fill_manual(values = c("#dac291","#41ae76", "#75638b"))+
  theme_bw() +
  labs(title= "A. Mothers' change of language use", subtitle = "French")+
  theme(axis.text.x = element_text(size=30),legend.position = "none", plot.title = element_text(size=35),
        plot.subtitle = element_text(size=30), axis.title=element_blank())+
      annotate("richtext", x=c(1,1,1), y=c(5,-9,-20), label=c(20,11,5), size=10)+ #Adding the N at time 1
  annotate("richtext", x=c(2,2,2), y=c(5,-9,-20), label=c(16,17,3), size=10) #Adding the N at time 2

mom_eng_node_counts <- mom_long_eng_s %>%
    filter(x=="time 1") %>%
  group_by(node) %>%
  summarise(count = n()) %>%
  ungroup()

mom_eng_next_node_counts <-  mom_long_eng_s %>%
 filter(x=="time 1") %>%
  group_by(next_node) %>%
  summarise(count = n()) %>%
  ungroup()


figure_3_b <- ggplot(mom_long_eng_s , aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node), label=node)) +
  geom_sankey(flow.color = "black") + 
  scale_fill_manual(values = c("#dac291","#41ae76", "#75638b"), name="language use with child frequency")+
  theme_bw() +
  labs(title= "A. Mothers' change of language use", subtitle = "English")+
  theme(axis.text.x = element_text(size=30),legend.text = element_text(size=30),legend.title = element_text(size=30), plot.title = element_text(size=35),
        plot.subtitle = element_text(size=30), axis.title=element_blank())+
      annotate("richtext", x=c(1,1,1), y=c(6,-10,-20), label=c(24, 8, 4), size=10)+ #Adding the N at time 1
  annotate("richtext", x=c(2,2,2), y=c(5,-10,-20), label=c(26,7,3), size=10) #Adding the N at time 2

library(cowplot)
figure_3<- plot_grid(figure_3_a, figure_3_b, ncol=2, rel_widths = c(2,3))

ggsave(file="Figure_3.png", width=25, height=12, dpi=300)

#### Father sankey


dad_long<- FE_long_analyses %>% #this results in a dataframe that has one row per kid who had 2 FR-EN visits.
    filter(type_of_family == "mother-father family") %>%
  filter(!strategy=="single-parent") %>%
  filter(visit %in% c(1,2)) %>% 
  select(anon_baby_id, l1, l2, care2_l1, care2_l2, visit, length_between_visits) %>%
    mutate(caregiver_2_french_use = case_when(l1=="French"~care2_l1,
                                            l2=="French"~care2_l2)) %>%
    mutate(caregiver_2_english_use = case_when(l1=="English"~care2_l1,
                                            l2=="English"~care2_l2),
           visit = paste0("time_", visit)) %>%
  rename("Fre" = caregiver_2_french_use,
         "Eng" = caregiver_2_english_use) %>%
  select(-care2_l1, -care2_l2, -l1, -l2) %>%
  pivot_wider(names_from = visit, values_from = c(Fre, Eng)) %>%
  rename_at(vars(starts_with("Fre")), ~ paste0(str_remove(., "Fre_"), "_Fre")) %>%
  rename_at(vars(starts_with("Eng")), ~  paste0(str_remove(., "Eng_"), "_Eng")) %>%
  drop_na()

dad_long_french<- dad_long %>%
  select(anon_baby_id, length_between_visits, time_1_Fre, time_2_Fre) %>%
mutate(time_1_Fre = case_when(time_1_Fre == "NA"~"never",
                               TRUE~ time_1_Fre))

dad_long_english<- dad_long %>%
  select(anon_baby_id, length_between_visits, time_1_Eng, time_2_Eng)

dad_long_fre_s <- dad_long_french %>%
      rename("time 1" = "time_1_Fre") %>%
  rename("time 2" = "time_2_Fre") %>%
  make_long("time 1","time 2") 


dad_long_fre_s$node <- factor(dad_long_fre_s$node, levels= c("never","sometimes", "regularly"))
dad_long_fre_s$next_node <- factor(dad_long_fre_s$next_node, levels= c("never","sometimes","regularly"))

dad_long_eng_s <- dad_long_english %>%
      rename("time 1" = "time_1_Eng") %>%
  rename("time 2" = "time_2_Eng") %>%
  make_long("time 1","time 2") 

dad_long_eng_s$node <- factor(dad_long_eng_s$node, levels= c("never","sometimes", "regularly"))
dad_long_eng_s$next_node <- factor(dad_long_eng_s$next_node, levels= c("never","sometimes","regularly"))

v1_dad_prop_fre <- dad_long %>%
  select(time_1_Fre, time_1_Eng) %>%
  group_by(time_1_Fre) %>%
  tally(name = "n_first_visit")%>%
  mutate(proportion_first_visit = n_first_visit/sum(n_first_visit)) %>%
  mutate(percentage_first_visit= proportion_first_visit*100)

v2_dad_prop_fre <- dad_long %>%
  select(time_2_Fre, time_2_Eng) %>%
  group_by(time_2_Fre) %>%
  tally(name = "n_first_visit")%>%
  mutate(proportion_first_visit = n_first_visit/sum(n_first_visit)) %>%
  mutate(percentage_first_visit= proportion_first_visit*100)


v1_dad_prop_eng <- dad_long %>%
  select(time_1_Fre, time_1_Eng) %>%
  group_by(time_1_Eng) %>%
  tally(name = "n_first_visit")%>%
  mutate(proportion_first_visit = n_first_visit/sum(n_first_visit)) %>%
  mutate(percentage_first_visit= proportion_first_visit*100)

v2_dad_prop_eng <- dad_long %>%
  select(time_2_Fre, time_2_Eng) %>%
  group_by(time_2_Eng) %>%
  tally(name = "n_first_visit")%>%
  mutate(proportion_first_visit = n_first_visit/sum(n_first_visit)) %>%
  mutate(percentage_first_visit= proportion_first_visit*100)


dad_fre_node_counts <- dad_long_fre_s %>%
    filter(x=="time 1") %>%
  group_by(node) %>%
  summarise(count = n()) %>%
  ungroup()

dad_fre_next_node_counts <-  dad_long_fre_s %>%
 filter(x=="time 1") %>%
  group_by(next_node) %>%
  summarise(count = n()) %>%
  ungroup()

figure_4_a <- ggplot(dad_long_fre_s , aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node), label=node)) +
  geom_sankey(flow.color = "black") +
    scale_fill_manual(values = c("#dac291","#41ae76", "#75638b"))+
  theme_bw()+
  theme(axis.text.x = element_text(size=30), legend.position = "none", plot.title = element_text(size=35), plot.subtitle = element_text(size = 30))+
  labs(title= "A. Fathers' change of language use", subtitle = "French")+
      annotate("richtext", x=c(1,1,1), y=c(5,-10,-20), label=c(22, 8, 6), size=10)+ #Adding the N at time 1
  annotate("richtext", x=c(2,2,2), y=c(5,-10,-20), label=c(23,8,5), size=10) #Adding the N at time 2


dad_eng_node_counts <- mom_long_eng_s %>%
    filter(x=="time 1") %>%
  group_by(node) %>%
  summarise(count = n()) %>%
  ungroup()

dad_eng_next_node_counts <-  dad_long_eng_s %>%
 filter(x=="time 1") %>%
  group_by(next_node) %>%
  summarise(count = n()) %>%
  ungroup()


figure_4_b <- ggplot(dad_long_eng_s , aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node), label=node)) +
  geom_sankey(flow.color = "black") + 
    scale_fill_manual(values =c("#dac291","#41ae76", "#75638b"), name="language use with child frequency")+
  theme_bw()+
  theme(axis.text.x = element_text(size=30), plot.title = element_text(size=35), axis.title = element_blank(), legend.text = element_text(size=30), legend.title = element_text(size=30), plot.subtitle = element_text(size = 30))+
  labs(title= "B. Fathers' change of language use", subtitle = "English")+
      annotate("richtext", x=c(1,1,1), y=c(4,-10,-22), label=c(24,8,4), size=10)+ #Adding the N at time 1
  annotate("richtext", x=c(2,2,2), y=c(4,-10,-22), label=c(20,9,7), size=10) #Adding the N at time 2


figure_4<- plot_grid(figure_4_a, figure_4_b, ncol=2, rel_widths = c(2,3))

ggsave(file="Figure_4.png", width=25, height=12, dpi=300)

### Parents' Logistic model

for_mother_glmer <- mom_long  %>%
  mutate(French_change = case_when(time_1_Fre == time_2_Fre ~ "No change",
                                   TRUE~ "change")) %>%
  mutate(English_change = case_when(time_1_Eng == time_2_Eng ~ "No change",
                                   TRUE~ "change"))


for_father_glmer <- dad_long  %>%
  mutate(French_change = case_when(time_1_Fre == time_2_Fre ~ "No change",
                                   TRUE~ "change")) %>%
  mutate(English_change = case_when(time_1_Eng == time_2_Eng ~ "No change",
                                   TRUE~ "change"))


mother_long_prop<- for_mother_glmer %>%
group_by(French_change, English_change) %>%
  tally() 

father_long_prop<- for_father_glmer %>%
group_by(French_change, English_change) %>%
  tally() 

#Mother change model

mother_french_change_model<- glmer(as.factor(French_change) ~ scale(length_between_visits) +(1|anon_baby_id), data = for_mother_glmer, family="binomial")

summary(mother_french_change_model)

mother_english_change_model<- glmer(as.factor(English_change) ~ scale(length_between_visits) +(1|anon_baby_id), data = for_mother_glmer, family="binomial")

summary(mother_english_change_model)


#Father change model

father_french_change_model<- glmer(as.factor(French_change) ~ scale(length_between_visits) +(1|anon_baby_id), data = for_father_glmer, family="binomial")

summary(father_french_change_model)

father_english_change_model<- glmer(as.factor(English_change) ~ scale(length_between_visits) +(1|anon_baby_id), data = for_father_glmer, family="binomial")

summary(father_english_change_model)

```






## Study 2: French/English-- heritage data analyses

```{r study 2 proportion of strategy use visualizations, include=FALSE }
###### FOR THE FRENCH- HERITAGE SAMPLE ###########
#Calculating how many families use each strategy and its corresponding %
her_prop_strategy<- FEH %>%
  filter(!bilingual_type == "fre-eng")%>%
group_by(strategy) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

#Reordering levels so legend in the graph is in order.
her_prop_strategy$strategy<- factor(her_prop_strategy$strategy, levels= c("one-parent-bilingual","both-parents-bilingual", "one-parent-one-lang", "single-parent", "one-language-at-home"))

her_prop_strategy<- her_prop_strategy %>%
 arrange(desc(prop))

#Waffle plot
her_V1<- setNames(her_prop_strategy$n, c( "one-parent-bilingual","both-parents-bilingual","one-parent-one-lanaguage",  "single-parent", "one-language-at-home"))

figure_5 <- waffle(parts = her_V1, rows=6, colors = c(my_yellow, my_orange, my_blue, my_purple, my_green), keep = T, size=0.6) + annotate("richtext", x=c(2,6,9), y=4, label=c("24", "18", "12"), size=10) +
  annotate("richtext", x=10, y=2, label= "4", size=10)+
  annotate("richtext", x=10, y=6, label= "2", size=10)+
 theme(legend.text= element_text(size=18),legend.title= element_text(size=18)) 

ggsave(file="Figure_5.png", width=25, height=7, dpi=300)

```


```{r study 2 chisq tests, include=FALSE}
her_for_chisq <- her_prop_strategy %>%
  filter(!strategy %in% c("single-parent", "one-language-at-home")) 


her_xsq_test<- chisq.test(her_for_chisq$n)


```


```{r Study 2: Mother and father language exploration, include=FALSE}

### Looking at the individual parent strategies in each family language strategy

##Both parents bilingual
her_both_parent_b<- FEH %>%
  filter(type_of_family == "mother-father family") %>%
  filter(!bilingual_type == "fre-eng")%>%
  filter(strategy=="both-parents-bilingual") %>%
  mutate(caregiver1_French =  case_when (l1== "French"~care1_l1,
                                         l2== "French"~care1_l2)) %>%
    mutate(caregiver1_English =  case_when (l1== "English"~care1_l1,
                                         l2== "English"~care1_l2)) %>%
      mutate(caregiver1_heritage =  case_when (l1== "Heritage"~care1_l1,
                                         l2== "Heritage"~care1_l2)) %>%
    mutate(caregiver2_French =  case_when (l1== "French"~care2_l1,
                                         l2== "French"~care2_l2)) %>%
    mutate(caregiver2_English =  case_when (l1== "English"~care2_l1,
                                         l2== "English"~care2_l2)) %>%
      mutate(caregiver2_heritage =  case_when (l1== "Heritage"~care2_l1,
                                         l2== "Heritage"~care2_l2)) %>%
  mutate(mom_use_strategy = case_when( caregiver1_heritage == "regularly" & caregiver1_heritage == "regularly" ~ "both regularly",
                                       caregiver1_French == "regularly" & caregiver1_heritage == "regularly" ~ "both regularly",
                                       caregiver1_English == "regularly" & caregiver1_heritage == "regularly" ~ "both regularly",
                                       caregiver1_French == "regularly" & caregiver1_heritage == "sometimes" ~ "french-reg-heritage-some",
                                       caregiver1_French == "sometimes" & caregiver1_heritage == "regularly" ~ "french-some-heritage-reg",
                                       caregiver1_English == "regularly" & caregiver1_heritage == "sometimes" ~ "english-reg-heritage-some",
                                       caregiver1_English == "sometimes" & caregiver1_heritage == "regularly" ~ "english-some-heritage-reg",
))%>%
  mutate(dad_use_strategy = case_when( caregiver2_heritage == "regularly" & caregiver2_heritage == "regularly" ~ "both regularly",
                                       caregiver2_French == "regularly" & caregiver2_heritage == "regularly" ~ "both regularly",
                                       caregiver2_English == "regularly" & caregiver2_heritage == "regularly" ~ "both regularly",
                                       caregiver2_French == "regularly" & caregiver2_heritage == "sometimes" ~ "french-reg-heritage-some",
                                       caregiver2_French == "sometimes" & caregiver2_heritage == "regularly" ~ "french-some-heritage-reg",
                                       caregiver2_English == "regularly" & caregiver2_heritage == "sometimes" ~ "english-reg-heritage-some",
                                       caregiver2_English == "sometimes" & caregiver2_heritage == "regularly" ~ "english-some-heritage-reg",
                                       TRUE~"both-sometimes")) 

# what are the percentages ?
her_mom_biling_strat<- her_both_parent_b %>%
  group_by(mom_use_strategy) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

her_dad_biling_strat<- her_both_parent_b %>%
  group_by(dad_use_strategy) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)



## One-parent-bilingual

#Which parent is the bilingual parent?
her_one_parent_b<- FEH %>%
  filter(type_of_family == "mother-father family") %>%
  filter(!bilingual_type == "fre-eng") %>%
  filter(strategy=="one-parent-bilingual") %>%
    mutate(caregiver_biling = case_when(care1_l1 %in% c("regularly", "sometimes") & care1_l2 %in% c("regularly", "sometimes") ~ "caregiver1",
                                      TRUE ~ "caregiver2"))
#What are the percentages
her_caregiver_bi_prop <- her_one_parent_b %>%
  group_by(caregiver_biling) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100) ## 67% mothers are the bilingual caregiver

#Which languages are spoken by the monolingual parent?

her_monoling_careg_lang<- her_one_parent_b %>%
  mutate(monolingual_care_lang = case_when(caregiver_biling == "caregiver1" & care2_l1 %in% c("regularly", "sometimes") ~ l1,
                                           caregiver_biling == "caregiver1" & care2_l2 %in% c("regularly", "sometimes") ~ l2,
                                           caregiver_biling == "caregiver2" & care1_l1 %in% c("regularly", "sometimes") ~l1,
                                           caregiver_biling == "caregiver2" & care1_l2 %in% c("regularly", "sometimes") ~l2)) %>%
  group_by(monolingual_care_lang) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100) ## 69% on the parents who are monolingual speak English
                                    
  

##Also looking at OPOL strategy

her_opol<- FEH %>%
  filter(type_of_family == "mother-father family") %>%
  filter(!bilingual_type == "fre-eng") %>%
  filter(strategy=="one-parent-one-lang") %>%
  mutate(parents_flexible_use = case_when( care1_l1 == "sometimes"| care1_l2 == "sometimes"|care2_l1 == "sometimes"|care2_l2 == "sometimes" ~ "flex_use",
                                           TRUE ~ "strict_use"
  ))


her_flex_opol_count<- her_opol %>%
  group_by(parents_flexible_use) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

her_opol_flex<- her_opol %>%
  filter(parents_flexible_use == "flex_use") %>%
  mutate(flex_parent = case_when(care1_l1 == "sometimes" | care1_l2  == "sometimes" ~ "mom",
                                  TRUE~ "dad"))

her_opol_strict<- her_opol %>%
  filter(!parents_flexible_use == "flex_use") 

her_opol_parent_count<- her_opol_flex %>%
  group_by(flex_parent) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(perc= prop*100)

## Which language is spoken by which parent 

l1_by_mother <- FEH %>%
filter(type_of_family == "mother-father family") %>%
  filter(!bilingual_type == "fre-eng") %>%
  group_by(l1, care1_l1) %>%
  tally()

l1_by_father <- FEH%>%
filter(type_of_family == "mother-father family") %>%
  filter(!bilingual_type == "fre-eng") %>%
  group_by(l1, care2_l1)%>%
  tally()

l2_by_mother <- FEH %>%
filter(type_of_family == "mother-father family") %>%
  filter(!bilingual_type == "fre-eng") %>%
  group_by(l2, care1_l2) %>%
  tally()

l2_by_father <- FEH%>%
filter(type_of_family == "mother-father family") %>%
  filter(!bilingual_type == "fre-eng") %>%
  group_by(l2, care2_l2)%>%
  tally()

```


```{r Study 2: linear models analysis, include=FALSE}

her_for_lms <- FEH %>%
    filter(!bilingual_type == "fre-eng") %>% 
  mutate(care1_l2 = case_when(care1_l2 =="NA" ~ "never",
                              TRUE ~ care1_l2)) %>%  
    mutate(care2_l1 = case_when(care2_l1 =="NA" ~ "never",
                              TRUE ~ care2_l1)) %>%
      mutate(care2_l2 = case_when(care2_l2 =="NA" ~ "never",
                              TRUE ~ care2_l2))  %>%
  mutate(caregiver_1_french_use = case_when(l1=="French"~care1_l1,
                                            l2=="French"~care1_l2)) %>%
    mutate(caregiver_1_heritage_use = case_when(l1=="Heritage"~care1_l1,
                                            l2=="Heritage"~care1_l2)) %>%
    mutate(caregiver_1_english_use = case_when(l1=="English"~care1_l1,
                                            l2=="English"~care1_l2)) %>%
    mutate(caregiver_2_french_use = case_when(l1=="French"~ care2_l1,
                                            l2=="French"~ care2_l2)) %>%
      mutate(caregiver_2_heritage_use = case_when(l1=="Heritage"~ care2_l1,
                                            l2=="Heritage"~ care2_l2)) %>%
    mutate(caregiver_2_english_use = case_when(l1=="English"~care2_l1,
                                            l2=="English"~care2_l2)) %>%
  filter(gender != "NA") %>%
  filter(!strategy %in% c("one-language-at-home", "single-parent")) %>%
  mutate(fre_exp = fre_exp/100, eng_exp = eng_exp/100, min_exp = min_exp/100) 

#French-Heritage models
freher_for_lms <- her_for_lms %>%
  filter(bilingual_type == "fre-her")

engher_for_lms <- her_for_lms %>%
  filter(bilingual_type == "eng-her")


#STRATEGY LINEAR MODELS
her_lm_strat_eng<- lm(eng_exp ~ strategy, data=her_for_lms)
her_lm_strat_fre <- lm(fre_exp ~ strategy, data=her_for_lms)
her_lm_strat_her <- lm(min_exp ~ strategy, data=her_for_lms)

#With the new datasets

engher_lm_strat_eng<- lm(eng_exp ~ strategy, data=engher_for_lms )
freher_lm_strat_fre <- lm(fre_exp ~ strategy, data=freher_for_lms)
engher_lm_strat_her <- lm(min_exp ~ strategy, data=engher_for_lms)
freher_lm_strat_her <- lm(min_exp ~ strategy, data=freher_for_lms)


#Summary of STRATEGY LINEAR models
summary(her_lm_strat_eng) #Slightly different, one parent bilingual is just a tad significant here and not for beta. 
summary(her_lm_strat_fre) #Same as above, one parent bilingual is significant and not for beta.
summary(her_lm_strat_her) 

summary(engher_lm_strat_eng)
summary(freher_lm_strat_fre)

###### Careviver models 
 her_parents_for_lms <- her_for_lms %>%
  filter(type_of_family == "mother-father family") 

#MOTHER MODELS
her_lm_mom_eng<- lm(eng_exp ~ caregiver_1_english_use, data=her_for_lms)
her_lm_mom_fre<- lm(fre_exp ~ caregiver_1_french_use, data=her_for_lms)
her_lm_mom_her<- lm(min_exp ~ caregiver_1_heritage_use, data=her_for_lms)

#Summary of MOTHER models
summary(her_lm_mom_eng) 
summary(her_lm_mom_fre) 
summary(her_lm_mom_her)

#FATHER MODELS 
her_lm_dad_eng<- lm(eng_exp ~ caregiver_2_english_use, data=her_for_lms)
her_lm_dad_fre<- lm(fre_exp ~ caregiver_2_french_use, data=her_for_lms)
her_lm_dad_her<- lm(min_exp ~ caregiver_2_heritage_use, data=her_for_lms)


#Summary of FATHER models
summary(her_lm_dad_eng) 
summary(her_lm_dad_fre) 
summary(her_lm_dad_her)


#MOTHER AND FATHER MODELS
her_lm_parents_aditive_eng<- lm(eng_exp ~ caregiver_2_english_use + caregiver_1_english_use, data=her_for_lms)
her_lm_parents_aditive_fre<- lm(fre_exp ~ caregiver_2_french_use + caregiver_1_french_use, data=her_for_lms)
her_lm_parents_aditive_her<- lm(min_exp ~ caregiver_2_heritage_use + caregiver_1_heritage_use, data=her_for_lms)

#Summary of Mother and Father models
summary(her_lm_parents_aditive_eng) 
summary(her_lm_parents_aditive_fre) 
summary(her_lm_parents_aditive_her) 



performance::compare_performance(her_lm_parents_aditive_fre, her_lm_dad_fre, her_lm_mom_fre)
performance::compare_performance(her_lm_parents_aditive_eng, her_lm_dad_eng, her_lm_mom_eng)
performance::compare_performance(her_lm_parents_aditive_her, her_lm_dad_her, her_lm_mom_her)

##Comparison of strategy versus parents models
performance::compare_performance(her_lm_parents_aditive_fre, her_lm_strat_fre)
performance::compare_performance(her_lm_parents_aditive_eng, her_lm_strat_eng)
performance::compare_performance(her_lm_parents_aditive_her, her_lm_strat_her)

```



```{r EXTRA ANALYSES: beta model Study 1, include=FALSE}

# Create the dataframes to run the models for each language. Monolinguals are excluded, as are the rows 
# where exposure for a given language equals 100. Since exposure is on a 0-100 scale and the beta distributions 
# works with values ranging from 0-1, exposure is divided by 100. 

for_beta <- FE_for_anovas %>% 
  select(gender, anon_baby_id, age, exp_l2, fre_exp, eng_exp, strategy, care1_l1, care1_l2, care2_l1, care2_l2, l1, l2) %>% 
  mutate(care1_l2 = case_when(care1_l2 =="NA" ~ "never",
                              TRUE ~ care1_l2)) %>%  #2023-07 going to need to fix this NAs in the cleaning script
    mutate(care2_l1 = case_when(care2_l1 =="NA" ~ "never",
                              TRUE ~ care2_l1)) %>%
      mutate(care2_l2 = case_when(care2_l2 =="NA" ~ "never",
                              TRUE ~ care2_l2)) %>%
  mutate(caregiver_1_french_use = case_when(l1=="French"~care1_l1,
                                            l2=="French"~care1_l2)) %>%
    mutate(caregiver_1_english_use = case_when(l1=="English"~care1_l1,
                                            l2=="English"~care1_l2)) %>%
    mutate(caregiver_2_french_use = case_when(l1=="French"~ care2_l1,
                                            l2=="French"~ care2_l2)) %>%
    mutate(caregiver_2_english_use = case_when(l1=="English"~care2_l1,
                                            l2=="English"~care2_l2)) %>%
  filter(gender != "NA") %>%
  filter(!strategy == "OneLanguageAtHome") %>%
  mutate(fre_exp = fre_exp/100, eng_exp = eng_exp/100, exp_l2 = exp_l2/100) %>%
  drop_na()

  

#Constructing the different beta models

#STRATEGY MODELS
strat_eng<- glmmTMB(eng_exp ~ strategy, data=for_beta, family= beta_family(link="logit"), dispformula = ~ strategy)
strat_fre <- glmmTMB(fre_exp ~ strategy, data=for_beta, family= beta_family(link="logit"), dispformula = ~ strategy)

#Summary of STRATEGY models
summary(strat_eng)
summary(strat_fre)


#MOTHER MODELS
mom_beta_eng<- glmmTMB(eng_exp ~ caregiver_1_english_use, data=for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_1_english_use)
mom_beta_fre<- glmmTMB(fre_exp ~ caregiver_1_french_use, data=for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_1_french_use)


#Summary of MOTHER models
summary(mom_beta_eng)
summary(mom_beta_fre)


#FATHER MODELS 
dad_beta_eng<- glmmTMB(eng_exp ~ caregiver_2_english_use, data=for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_2_english_use)
dad_beta_fre<- glmmTMB(fre_exp ~ caregiver_2_french_use, data=for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_2_french_use)


#Summary of FATHER models
summary(dad_beta_eng)
summary(dad_beta_fre)


#MOTHER AND FATHER MODELS
parents_aditive_eng<- glmmTMB(eng_exp ~ caregiver_2_english_use + caregiver_1_english_use, data=for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_2_english_use + caregiver_1_english_use)

parents_aditive_fre<- glmmTMB(fre_exp ~ caregiver_2_french_use + caregiver_1_french_use, data=for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_2_french_use + caregiver_1_french_use)


#Summary of Mother and Father models
summary(parents_aditive_eng)
summary(parents_aditive_fre)

## MODEL COMPARISONS
#ENGLISH MODELS
test_performance(parents_aditive_eng, mom_beta_eng)
test_performance(parents_aditive_eng, dad_beta_eng)

#DHARMa::simulateLRT(mom_beta_eng, parents_aditive_eng, n=100) #aditive model is better


#FRENCH MODELS
test_performance(parents_aditive_fre, mom_beta_fre)
test_performance(parents_aditive_fre, dad_beta_fre)

performance::compare_performance(parents_aditive_fre, mom_beta_fre, dad_beta_fre)

#DHARMa::simulateLRT(mom_beta_fre, parents_aditive_fre, n=100) 


 summary(parents_aditive_fre)
 summary(parents_aditive_eng)



##Notes by Nico: The dispersion model is not interpretable if the conditional model is not significative. If the dispersion model is significative the only thing it means is that the variance between predictors is different from eachother. 

##Negative AIC is fine, it is interpreted as usual, the smaller the better

```


```{r EXTRA ANALYSES:beta model Study 1, include=FALSE}


her_for_beta  <- her_for_anovas %>% 
  select(gender, anon_baby_id, age, exp_l2, min_exp,fre_exp, eng_exp, strategy, care1_l1, care1_l2, care2_l1, care2_l2, l1, l2) %>% 
  mutate(care1_l2 = case_when(care1_l2 =="NA" ~ "never",
                              TRUE ~ care1_l2)) %>%  
    mutate(care2_l1 = case_when(care2_l1 =="NA" ~ "never",
                              TRUE ~ care2_l1)) %>%
      mutate(care2_l2 = case_when(care2_l2 =="NA" ~ "never",
                              TRUE ~ care2_l2))  %>%
  mutate(caregiver_1_french_use = case_when(l1=="French"~care1_l1,
                                            l2=="French"~care1_l2)) %>%
    mutate(caregiver_1_heritage_use = case_when(l1=="Heritage"~care1_l1,
                                            l2=="Heritage"~care1_l2)) %>%
    mutate(caregiver_1_english_use = case_when(l1=="English"~care1_l1,
                                            l2=="English"~care1_l2)) %>%
    mutate(caregiver_2_french_use = case_when(l1=="French"~ care2_l1,
                                            l2=="French"~ care2_l2)) %>%
      mutate(caregiver_2_heritage_use = case_when(l1=="Heritage"~ care2_l1,
                                            l2=="Heritage"~ care2_l2)) %>%
    mutate(caregiver_2_english_use = case_when(l1=="English"~care2_l1,
                                            l2=="English"~care2_l2)) %>%
  filter(gender != "NA") %>%
  filter(!strategy == "OneLanguageAtHome") %>%
  mutate(fre_exp = fre_exp/100, eng_exp = eng_exp/100, min_exp = min_exp/100) 

#Constructing the different beta models

#STRATEGY MODELS
her_strat_eng<- glmmTMB(eng_exp ~ strategy, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ strategy)
her_strat_fre <- glmmTMB(fre_exp ~ strategy, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ strategy)
her_strat_her <- glmmTMB(min_exp ~ strategy, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ strategy)

#Summary of STRATEGY models
summary(her_strat_eng)
summary(her_strat_fre)
summary(her_strat_her)

#MOTHER MODELS
her_mom_beta_eng<- glmmTMB(eng_exp ~ caregiver_1_english_use, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_1_english_use)
her_mom_beta_fre<- glmmTMB(fre_exp ~ caregiver_1_french_use, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_1_french_use)
her_mom_beta_her<- glmmTMB(min_exp ~ caregiver_1_heritage_use, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_1_heritage_use)


#Summary of MOTHER models
summary(her_mom_beta_eng)
summary(her_mom_beta_fre)
summary(her_mom_beta_her)


#FATHER MODELS 
her_dad_beta_eng<- glmmTMB(eng_exp ~ caregiver_2_english_use, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_2_english_use)
her_dad_beta_fre<- glmmTMB(fre_exp ~ caregiver_2_french_use, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_2_french_use)
her_dad_beta_her<- glmmTMB(min_exp ~ caregiver_2_heritage_use, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_2_heritage_use)


#Summary of FATHER models
summary(dad_beta_eng)
summary(dad_beta_fre)
summary(her_dad_beta_her)


#MOTHER AND FATHER MODELS
her_parents_aditive_eng<- glmmTMB(eng_exp ~ caregiver_2_english_use + caregiver_1_english_use, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_2_english_use + caregiver_1_english_use)

her_parents_aditive_fre<- glmmTMB(fre_exp ~ caregiver_2_french_use + caregiver_1_french_use, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_2_french_use + caregiver_1_french_use)

her_parents_aditive_her<- glmmTMB(min_exp ~ caregiver_2_heritage_use + caregiver_1_french_use, data=her_for_beta, family= beta_family(link="logit"), dispformula = ~ caregiver_2_french_use + caregiver_1_heritage_use)


#Summary of Mother and Father models
summary(her_parents_aditive_eng)
summary(her_parents_aditive_fre)
summary(her_parents_aditive_her)

```


```{r Other visualization}
library(sjPlot)
library(sjlabelled)
library(sjmisc)

ov1_labels<- c("mother use sometimes", "mother use regularly", "father use sometimes", "father use regularly", "mother use sometimes", "mother use regularly","father use sometimes", "father use regularly")

ov1<- plot_models(lm_parents_aditive_eng, lm_parents_aditive_fre, show.values = TRUE, show.p = T, title = "A.Individual Parents' Contributions Model Estimates- French-English Sample", axis.labels = ov1_labels, axis.lim = c(-1,1), vline.color = "black", colors = c(my_blue, "red"), m.labels= c("Eng exp", "Fre exp"))+ theme_bw() +
   theme(axis.text.y = element_text(size=13), axis.title.x = element_text(size=13), legend.text = element_text(size=13), legend.title = element_text(size=13)) 


ov2_labels<- c("mother use sometimes", "mother use regularly", "father use sometimes", "father use regularly", "mother use sometimes", "mother use regularly","father use sometimes", "father use regularly", "mother use sometimes", "mother use regularly","father use sometimes", "father use regularly")


ov2<- plot_models(her_lm_parents_aditive_eng, her_lm_parents_aditive_fre, her_lm_parents_aditive_her, show.values = T, show.p = T, title = "B.Individual Parents' Contributions Model Estimates- Heritage Sample", axis.labels = ov2_labels, axis.lim = c(-1,1), vline.color = "black", colors = c(my_green, my_blue, "red"), m.labels= c("Eng exp", "Fre exp", "Heritage exp"))+ theme_bw()+
  theme(axis.text.y = element_text(size=13), axis.title.x = element_text(size=13), legend.text = element_text(size=13), legend.title = element_text(size=13)) 


other_visualization<- ov1+ov2

print(other_visualization)
```





