---
title: "3_visualizations"
author: "ASM"
date: "27/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(ggsankey)
```

##------Load necessary data sets

```{r}

load(here("anonymized_data/longitudinal_data.Rda"))
load(here("anonymized_data/final_data_strat.Rda"))

```


##----Descriptive graphs
```{r}
#Descriptive graphs: 1 proportion of use statistic.

prop_strategy<-final_data_strat%>%
group_by(strategy) %>%
  tally() %>%
  mutate(prop = n/sum(n)) 

prop_strategy<- prop_strategy %>%
  mutate(strategy = fct_reorder(prop_strategy$strategy, prop_strategy$prop, .desc=F))

ggplot(prop_strategy, aes(x="", y=prop, fill=strategy)) +
  geom_bar (stat= "identity")+
  scale_fill_manual (name = "Family Strategy", values =c("#4d4d4d","#57bc53","#008c77", "#4169e1", "#f6cb7f", "#f94f80")) +
  labs(x="", title = "Proportion of Use of Family Strategies")+
  theme(axis.text.x= element_blank(), axis.ticks = element_blank())+
  theme_bw() 

#strategy by L2 exposure

final_data_strat <- final_data_strat %>%
  mutate(dom_lang_exp = case_when( exp_l1 >= 45 & exp_l1 <= 60 ~"45-60",
                              exp_l1 >= 60.1 & exp_l1 <=75 ~"60-75",
                              exp_l1 >=75.1 & exp_l1 <= 90 ~"75-90",
                              exp_l1 >=90.1 & exp_l1 <=100 ~"90-100"))

prop_strategy_balance<-final_data_strat%>%
group_by(dom_lang_exp, strategy) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  mutate(strategy = fct_relevel(strategy, "single-parent", "one-parent-one-lang-strict","one-parent-one-lang-flex","one-language-at-home","one-parent-bilingual", "both-parents-bilingual"))


ggplot(prop_strategy_balance,aes( x=dom_lang_exp , y= prop, fill = strategy )) +
  geom_col() +
   scale_fill_manual (name = "Family Strategy", values =c("#4d4d4d","#57bc53","#008c77", "#4169e1", "#f6cb7f", "#f94f80")) +
  theme_bw() +
  labs(title= "Proportion of Use of Family Strategies by Dominant Language Exposure Bin")
```

##----- mean l1 exposure by strategy
```{r}

l1_by_strategy <- final_data_strat %>%
  select(c(strategy, exp_l1)) %>%
  group_by(strategy) %>%
  summarise(mean(exp_l1))

#columns
ggplot(l1_by_strategy,aes( x=strategy , y=`mean(exp_l1)`, fill = strategy )) +
  geom_col() +
   scale_fill_manual (name = "Family Strategy", values =c("#4d4d4d","#57bc53","#008c77", "#4169e1", "#f6cb7f", "#f94f80")) +
  theme_bw() +
  labs(title= "Mean l1 exposure by strategy")

```
##----- mean french exposure by strategy
```{r}
final_data_fre <- final_data_strat %>%
  mutate(fre_exp = case_when(l1 == "French" ~ exp_l1,
                             l2 == "French"~ exp_l2,
                             TRUE ~ 0))

fre_by_strategy <- final_data_fre  %>%
  select(c(strategy, fre_exp)) %>%
  group_by(strategy) %>%
  summarise(mean(fre_exp))


ggplot(fre_by_strategy, aes( x=strategy , y=`mean(fre_exp)`, fill = strategy )) +
  geom_col() +
   scale_fill_manual (name = "Family Strategy", values =c("#4d4d4d","#57bc53","#008c77", "#4169e1", "#f6cb7f", "#f94f80")) +
  theme_bw() +
  labs(title= "Mean french exposure by strategy")
```


##----- Sankey graph

```{r}
#select only relevant variables
longitudinal_data <- longitudinal_data %>%
  select(age, strategy, unique_id, anon_baby_id)

longitudinal_data<- longitudinal_data %>%
  arrange(anon_baby_id, age) %>%
  group_by(anon_baby_id) %>%
  mutate(visit = row_number()) %>%
  ungroup() 

wider_longitudinal <- longitudinal_data %>%
  select(anon_baby_id, visit, strategy) %>%
  filter(str_detect(strategy, "single-parent", negate=T))

wider_longitudinal <- pivot_wider(wider_longitudinal,
                                names_from = visit, values_from = strategy ) %>%
  rename(visit_1 = "1", visit_2 = "2", visit_3 ="3", visit_4 ="4" ) 



for_sankey <- wider_longitudinal %>%
  make_long(visit_1, visit_2) 

for_sankey <- for_sankey %>%
  mutate(node= fct_relevel (node, "both-parents-bilingual", "one-parent-bilingual", "one-language-at-home", "one-parent-one-lang-flex", "one-parent-one-lang-strict"))

p1<- ggplot(for_sankey, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node), label=node)) +
  geom_sankey() 

p2<- p1+ 
      scale_fill_manual(name= "x", values = c("#f94f80", "#f6cb7f", "#4169e1", "#008c77", "#57bc53"))

p2<- p2 + 
  geom_sankey_label(size=3, color="black", fill="white")+
  theme_bw()+
  theme(legend.position = "none", axis.ticks = element_blank(), axis.text.y = element_blank()) +
  labs(title="Stability of Family Strategies Across Visit", x="")
  

print(p2)


``` 


##----Exploratory graph not for manuscript
```{r}
#Probably not going to use in paper.

final_data_strat <- final_data_strat %>%
  mutate(dom_lang_exp = case_when( exp_l1 >= 45 & exp_l1 <= 60 ~"45-60",
                              exp_l1 >= 60.1 & exp_l1 <=75 ~"60-75",
                              exp_l1 >=75.1 & exp_l1 <= 90 ~"75-90",
                              exp_l1 >=90.1 & exp_l1 <=100 ~"90-100"))
    

for_sankey_2 <- final_data_strat %>%
  make_long(strategy, dom_lang_exp) 

p3<- ggplot(for_sankey_2, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node), label=node)) +
  geom_sankey() 


p3<- p3 + 
  geom_sankey_label(size=3, color="black", fill="white")+
  theme_bw()+
  theme(legend.position = "none", axis.ticks = element_blank(), axis.text.y = element_blank()) 

print(p3)
```

